// Generated by CoffeeScript 1.3.3
/*
Chess Move Generator: Unit tests
@author François Cardinaux, CH 1207 Genève
@copyright 2012 François Cardinaux

Licence: see README.md

About Expresso: http://visionmedia.github.com/expresso/

Profiling:

* Using [nodetime](http://nodetime.com/):

        sudo npm install nodetime

* NOT ON MACOSX / Using [dtrace and flamegraph](http://blog.nodejs.org/2012/04/25/profiling-node-js/):

        sudo dtrace -n 'profile-97/execname == "node" && arg1/{@[jstack(150, 8000)] = count(); } tick-60s { exit(0); }' > stacks.out
        sudo dtrace -n 'profile-97/pid == 1851 && arg1/{@[jstack(150, 8000)] = count(); } tick-60s { exit(0); }' > stacks.out
        stackvis dtrace flamegraph-svg < stacks.out > stacks.svg
*/

var DEPTH, DO_DIVISION_TEST, DO_ELEMENTARY_TESTS, DO_PERFTSUITE, DO_POSSIBLE_MOVE_TEST, LOG_DIVISION_TEST, LOG_ELEMENTARY_TEST, LOG_MOVE_TEST, LOG_PERFTSUITE, bitBoardClass, chessMoveGenerator, compareArrays, getInitialCounterArray, positionClass, testDepth, trimString, utilityClass;

DO_ELEMENTARY_TESTS = true;

DO_POSSIBLE_MOVE_TEST = false;

DO_DIVISION_TEST = false;

DO_PERFTSUITE = false;

DEPTH = 6;

LOG_ELEMENTARY_TEST = function(x) {};

LOG_MOVE_TEST = function(x) {};

LOG_DIVISION_TEST = function(x) {
  return console.log(x);
};

LOG_PERFTSUITE = function(x) {
  return console.log(x);
};

chessMoveGenerator = require('../javascript/chess-move-generator');

positionClass = chessMoveGenerator.position;

bitBoardClass = chessMoveGenerator.bitBoard;

utilityClass = chessMoveGenerator.utility;

getInitialCounterArray = function(maxDepth) {
  var counters, iDepth, _i, _ref;
  counters = [];
  for (iDepth = _i = 0, _ref = maxDepth - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; iDepth = 0 <= _ref ? ++_i : --_i) {
    counters.push(0);
  }
  return counters;
};

testDepth = function(positionObj, counters, currentDepth, maxDepth, logFunction) {
  var move, moveId, moveQuantity, moves, pos, _i, _len;
  if (logFunction == null) {
    logFunction = false;
  }
  moves = positionObj.allPossibleMoves();
  moveQuantity = moves.length;
  counters[currentDepth] += moveQuantity;
  currentDepth++;
  if (currentDepth >= maxDepth) {
    return true;
  }
  for (moveId = _i = 0, _len = moves.length; _i < _len; moveId = ++_i) {
    move = moves[moveId];
    if (logFunction) {
      logFunction("  * testing move " + (moveId + 1) + " of " + moveQuantity + " (" + (move.toString()) + ")");
    }
    pos = move.getNewPosition().clone(false, true);
    testDepth(pos, counters, currentDepth, maxDepth);
    move = null;
    pos = null;
  }
  moves = null;
  return true;
};

trimString = function(str) {
  return str.replace(/^\s\s*/, '').replace(/\s\s*$/, '');
};

compareArrays = function(arr1, arr2) {
  var elem1, elem2, lookup1, lookup2, missingInArr1, missingInArr2, _i, _j, _k, _len, _len1, _len2;
  missingInArr1 = [];
  missingInArr2 = [];
  lookup1 = {};
  for (_i = 0, _len = arr1.length; _i < _len; _i++) {
    elem1 = arr1[_i];
    lookup1[elem1] = elem1;
  }
  lookup2 = {};
  for (_j = 0, _len1 = arr2.length; _j < _len1; _j++) {
    elem2 = arr2[_j];
    lookup2[elem2] = elem2;
    if (typeof lookup1[elem2] === 'undefined') {
      missingInArr1.push(elem2);
    }
  }
  for (_k = 0, _len2 = arr1.length; _k < _len2; _k++) {
    elem1 = arr1[_k];
    if (typeof lookup2[elem1] === 'undefined') {
      missingInArr2.push(elem1);
    }
  }
  return [missingInArr1, missingInArr2];
};

module.exports = {
  'test CMGBitBoard#valueOfSquare': function(beforeExit, assert) {
    if (!DO_ELEMENTARY_TESTS) {
      return;
    }
    LOG_ELEMENTARY_TEST('Testing bitboard values of squares');
    assert.eql([0x0, 0x8000, 0x0, 0x0], bitBoardClass.valueOfSquare(31));
    assert.eql([0x1, 0x0, 0x0, 0x0], bitBoardClass.valueOfSquare(0));
    assert.eql([0x80, 0x0, 0x0, 0x0], bitBoardClass.valueOfSquare(7));
    assert.eql([0x100, 0x0, 0x0, 0x0], bitBoardClass.valueOfSquare(8));
    assert.eql([0x8000, 0x0, 0x0, 0x0], bitBoardClass.valueOfSquare(15));
    assert.eql([0x0, 0x1, 0x0, 0x0], bitBoardClass.valueOfSquare(16));
    assert.eql([0x0, 0x80, 0x0, 0x0], bitBoardClass.valueOfSquare(23));
    assert.eql([0x0, 0x100, 0x0, 0x0], bitBoardClass.valueOfSquare(24));
    assert.eql([0x0, 0x0, 0x1, 0x0], bitBoardClass.valueOfSquare(32));
    return assert.eql([0x0, 0x0, 0x0, 0x8000], bitBoardClass.valueOfSquare(63));
  },
  'test CMGPosition#fromString': function(beforeExit, assert) {
    var newPositionString, posObj, positionString, positionStrings, _i, _len, _results;
    if (!DO_ELEMENTARY_TESTS) {
      return;
    }
    LOG_ELEMENTARY_TEST('Testing string to and from position object');
    positionStrings = ["rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1", "8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - 0 0", "8/2p5/K2p4/1P5r/1R3p1k/8/4P1P1/8 b - - 1 0", "8/2p5/3p4/1P5r/KR3p1k/8/4P1P1/8 b - - 1 0", "8/2p5/3p4/KP5r/R4p1k/8/4P1P1/8 b - - 1 0", "8/2p5/3p4/KP5r/2R2p1k/8/4P1P1/8 b - - 1 0", "8/2p5/3p4/KP5r/3R1p1k/8/4P1P1/8 b - - 1 0", "8/2p5/3p4/KP5r/4Rp1k/8/4P1P1/8 b - - 1 0", "8/2p5/3p4/KP5r/5R1k/8/4P1P1/8 b - - 0 0", "8/2p5/3p4/KP5r/5p1k/1R6/4P1P1/8 b - - 1 0", "8/2p5/3p4/KP5r/5p1k/8/1R2P1P1/8 b - - 1 0", "8/2p5/3p4/KP5r/5p1k/8/4P1P1/1R6 b - - 1 0", "8/2p5/3p4/KP5r/1R3p1k/4P3/6P1/8 b - - 0 0", "8/2p5/3p4/KP5r/1R2Pp1k/8/6P1/8 b - e3 0 0", "8/2p5/3p4/KP5r/1R3p1k/6P1/4P3/8 b - - 0 0", "8/2p5/3p4/KP5r/1R3pPk/8/4P3/8 b - g3 0 0"];
    _results = [];
    for (_i = 0, _len = positionStrings.length; _i < _len; _i++) {
      positionString = positionStrings[_i];
      posObj = positionClass.fromString(positionString);
      assert.eql(true, posObj instanceof positionClass);
      newPositionString = posObj.toString();
      _results.push(assert.eql(positionString, newPositionString));
    }
    return _results;
  },
  'test CMGPosition#_allowedCastlingValueToString': function(beforeExit, assert) {
    if (!DO_ELEMENTARY_TESTS) {
      return;
    }
    LOG_ELEMENTARY_TEST('Testing allowed castling values to string');
    assert.eql("KQkq", positionClass._allowedCastlingValueToString(15));
    assert.eql("KQk", positionClass._allowedCastlingValueToString(14));
    assert.eql("KQq", positionClass._allowedCastlingValueToString(13));
    assert.eql("KQ", positionClass._allowedCastlingValueToString(12));
    assert.eql("Kkq", positionClass._allowedCastlingValueToString(11));
    assert.eql("Kk", positionClass._allowedCastlingValueToString(10));
    assert.eql("Kq", positionClass._allowedCastlingValueToString(9));
    assert.eql("K", positionClass._allowedCastlingValueToString(8));
    assert.eql("Qkq", positionClass._allowedCastlingValueToString(7));
    assert.eql("Qk", positionClass._allowedCastlingValueToString(6));
    assert.eql("Qq", positionClass._allowedCastlingValueToString(5));
    assert.eql("Q", positionClass._allowedCastlingValueToString(4));
    assert.eql("kq", positionClass._allowedCastlingValueToString(3));
    assert.eql("k", positionClass._allowedCastlingValueToString(2));
    assert.eql("q", positionClass._allowedCastlingValueToString(1));
    return assert.eql("-", positionClass._allowedCastlingValueToString(0));
  },
  'test CMGPosition#_allowedCastlingStringToValue': function(beforeExit, assert) {
    if (!DO_ELEMENTARY_TESTS) {
      return;
    }
    LOG_ELEMENTARY_TEST('Testing allowed castling values from string');
    assert.eql(15, positionClass._allowedCastlingStringToValue("KQkq"));
    assert.eql(14, positionClass._allowedCastlingStringToValue("KQk"));
    assert.eql(13, positionClass._allowedCastlingStringToValue("KQq"));
    assert.eql(12, positionClass._allowedCastlingStringToValue("KQ"));
    assert.eql(11, positionClass._allowedCastlingStringToValue("Kkq"));
    assert.eql(10, positionClass._allowedCastlingStringToValue("Kk"));
    assert.eql(9, positionClass._allowedCastlingStringToValue("Kq"));
    assert.eql(8, positionClass._allowedCastlingStringToValue("K"));
    assert.eql(7, positionClass._allowedCastlingStringToValue("Qkq"));
    assert.eql(6, positionClass._allowedCastlingStringToValue("Qk"));
    assert.eql(5, positionClass._allowedCastlingStringToValue("Qq"));
    assert.eql(4, positionClass._allowedCastlingStringToValue("Q"));
    assert.eql(3, positionClass._allowedCastlingStringToValue("kq"));
    assert.eql(2, positionClass._allowedCastlingStringToValue("k"));
    assert.eql(1, positionClass._allowedCastlingStringToValue("q"));
    return assert.eql(0, positionClass._allowedCastlingStringToValue("-"));
  },
  'test CMGPosition#playerColorCode': function(beforeExit, assert) {
    var colorCode, positionObj, positionString, testData, _i, _len, _ref, _results;
    if (!DO_ELEMENTARY_TESTS) {
      return;
    }
    LOG_ELEMENTARY_TEST('Testing player color code');
    testData = [['w', "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"], ['b', "4k3/8/R7/8/7b/8/3P4/7K b - - 33 32"], ['b', "rn2k2r/pppppppp/8/8/1P1P1P1P/8/P1P1P1P1/R3K2R b Kq e3 3 12"], ['w', "r3k2r/pppppppp/8/8/1P1P1P1P/8/P1P1P1P1/RN2K2R w Qk e6 3 12"]];
    _results = [];
    for (_i = 0, _len = testData.length; _i < _len; _i++) {
      _ref = testData[_i], colorCode = _ref[0], positionString = _ref[1];
      positionObj = positionClass.fromString(positionString);
      _results.push(assert.eql(colorCode, positionObj.playerColorCode()));
    }
    return _results;
  },
  'test CMGPosition#opponentColorCode': function(beforeExit, assert) {
    var colorCode, positionObj, positionString, testData, _i, _len, _ref, _results;
    if (!DO_ELEMENTARY_TESTS) {
      return;
    }
    LOG_ELEMENTARY_TEST('Testing opponent color code');
    testData = [['b', "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"], ['w', "4k3/8/R7/8/7b/8/3P4/7K b - - 33 32"], ['w', "rn2k2r/pppppppp/8/8/1P1P1P1P/8/P1P1P1P1/R3K2R b Kq e3 3 12"], ['b', "r3k2r/pppppppp/8/8/1P1P1P1P/8/P1P1P1P1/RN2K2R w Qk e6 3 12"]];
    _results = [];
    for (_i = 0, _len = testData.length; _i < _len; _i++) {
      _ref = testData[_i], colorCode = _ref[0], positionString = _ref[1];
      positionObj = positionClass.fromString(positionString);
      _results.push(assert.eql(colorCode, positionObj.opponentColorCode()));
    }
    return _results;
  },
  'test CMGUtil#0x88representation': function(beforeExit, assert) {
    var returnedKey, square0x88value, square0x88values, squareKey, _i, _results;
    if (!DO_ELEMENTARY_TESTS) {
      return;
    }
    LOG_ELEMENTARY_TEST('Testing square key conversion to and from 0x88 representation');
    square0x88values = [0, 1, 2, 3, 4, 5, 6, 7, 16, 17, 18, 19, 20, 21, 22, 23, 32, 33, 34, 35, 36, 37, 38, 39, 48, 49, 50, 51, 52, 53, 54, 55, 64, 65, 66, 67, 68, 69, 70, 71, 80, 81, 82, 83, 84, 85, 86, 87, 96, 97, 98, 99, 100, 101, 102, 103, 112, 113, 114, 115, 116, 117, 118, 119];
    _results = [];
    for (squareKey = _i = 0; _i <= 63; squareKey = ++_i) {
      square0x88value = utilityClass.to0x88representation(squareKey);
      assert.eql(square0x88value, square0x88values[squareKey], "0x88 representation of " + squareKey + " should be " + square0x88values[squareKey] + " and not " + square0x88value + ".");
      returnedKey = utilityClass.from0x88representation(square0x88value);
      _results.push(assert.eql(squareKey, returnedKey, "Square key of " + squareKey + " has 0x88 representation " + square0x88value + ", which is incorrectly converted back to " + returnedKey + "."));
    }
    return _results;
  },
  'test CMGPosition#isDraw': function(beforeExit, assert) {
    var draw, draws, nonDraw, nonDraws, pos, _i, _j, _len, _len1, _results;
    if (!DO_ELEMENTARY_TESTS) {
      return;
    }
    LOG_ELEMENTARY_TEST('Testing if specific positions are draw');
    draws = ['4k3/4P3/4K3/8/8/8/8/8 b - - 1 1'];
    for (_i = 0, _len = draws.length; _i < _len; _i++) {
      draw = draws[_i];
      pos = positionClass.fromString(draw);
      assert.eql(true, pos.isDraw(), "Position " + draw + " was supposed to be a draw, but isnt.");
    }
    nonDraws = ['4k3/4P3/4K3/8/8/8/8/8 w - - 1 1'];
    _results = [];
    for (_j = 0, _len1 = nonDraws.length; _j < _len1; _j++) {
      nonDraw = nonDraws[_j];
      pos = positionClass.fromString(nonDraw);
      _results.push(assert.eql(false, pos.isDraw(), "Position " + nonDraw + " was supposed NOT to be a draw, but is."));
    }
    return _results;
  },
  'test CMGPosition#getWinnerColorCode': function(beforeExit, assert) {
    var losingPosition, losingPositions, notLosingPosition, notLosingPositions, pos, _i, _j, _len, _len1, _results;
    if (!DO_ELEMENTARY_TESTS) {
      return;
    }
    LOG_ELEMENTARY_TEST('Testing if specific positions are losing');
    losingPositions = ['4k3/4Q3/4K3/8/8/8/8/8 b - - 1 1'];
    for (_i = 0, _len = losingPositions.length; _i < _len; _i++) {
      losingPosition = losingPositions[_i];
      pos = positionClass.fromString(losingPosition);
      assert.eql('w', pos.getWinnerColorCode(), "Position " + losingPosition + " was supposed to be losing, but isnt.");
    }
    notLosingPositions = ['4k3/4P3/4K3/8/8/8/8/8 w - - 1 1'];
    _results = [];
    for (_j = 0, _len1 = notLosingPositions.length; _j < _len1; _j++) {
      notLosingPosition = notLosingPositions[_j];
      pos = positionClass.fromString(notLosingPosition);
      _results.push(assert.eql(false, pos.getWinnerColorCode(), "Position " + notLosingPosition + " was supposed NOT to be losing, but is."));
    }
    return _results;
  },
  'test CMGPosition#allPossibleMoves': function(beforeExit, assert) {
    var calculatedEndPositionStrings, calculatedMove, calculatedMoves, eps, expectedEndPositionStrings, positionObj, result, startPositionString, testVector, _i, _j, _k, _len, _len1, _len2, _ref, _results;
    if (!DO_POSSIBLE_MOVE_TEST) {
      return;
    }
    LOG_MOVE_TEST('Testing all possible moves from given positions');
    testVector = require("../test-data/next-position-test");
    _results = [];
    for (_i = 0, _len = testVector.length; _i < _len; _i++) {
      _ref = testVector[_i], startPositionString = _ref[0], expectedEndPositionStrings = _ref[1];
      positionObj = positionClass.fromString(startPositionString);
      LOG_MOVE_TEST('Start = ' + startPositionString);
      LOG_MOVE_TEST('Expected: ');
      for (_j = 0, _len1 = expectedEndPositionStrings.length; _j < _len1; _j++) {
        eps = expectedEndPositionStrings[_j];
        LOG_MOVE_TEST(eps);
      }
      LOG_MOVE_TEST('Calculated: ');
      calculatedMoves = positionObj.allPossibleMoves();
      calculatedEndPositionStrings = [];
      for (_k = 0, _len2 = calculatedMoves.length; _k < _len2; _k++) {
        calculatedMove = calculatedMoves[_k];
        calculatedEndPositionStrings.push(calculatedMove.getNewPosition().toString());
      }
      result = compareArrays(expectedEndPositionStrings, calculatedEndPositionStrings);
      _results.push(assert.eql([[], []], result));
    }
    return _results;
  },
  'test division': function(beforeExit, assert) {
    var calculatedMoveId, calculatedMoveObj, calculatedMoveQty, calculatedMoveString, calculatedMoves, calculatedQuantity, counters, depth, expectedData, expectedMove, expectedQuantity, moveId, newDepth, position, positionString, testVector, _i, _j, _len, _len1, _ref, _results;
    if (!DO_DIVISION_TEST) {
      return;
    }
    testVector = require("../test-data/division-test");
    _results = [];
    for (_i = 0, _len = testVector.length; _i < _len; _i++) {
      _ref = testVector[_i], positionString = _ref[0], depth = _ref[1], expectedData = _ref[2];
      LOG_DIVISION_TEST("Verifying \"" + positionString + "\" at depth " + depth + ":");
      position = positionClass.fromString(positionString);
      calculatedMoves = {};
      calculatedMoves = position.allPossibleMoves();
      calculatedMoveQty = calculatedMoves.length;
      for (calculatedMoveId = _j = 0, _len1 = calculatedMoves.length; _j < _len1; calculatedMoveId = ++_j) {
        calculatedMoveObj = calculatedMoves[calculatedMoveId];
        calculatedMoveString = calculatedMoveObj.toString();
        LOG_DIVISION_TEST("  * calculated move " + (calculatedMoveId + 1) + " of " + calculatedMoveQty + " (" + calculatedMoveString + ")");
        assert.isDefined(expectedData[calculatedMoveString], "Unexpected move " + calculatedMoveString + " from position " + positionString);
        calculatedMoves[calculatedMoveString] = calculatedMoveObj;
      }
      moveId = 0;
      _results.push((function() {
        var _results1;
        _results1 = [];
        for (expectedMove in expectedData) {
          expectedQuantity = expectedData[expectedMove];
          moveId++;
          LOG_DIVISION_TEST("  * expected move " + moveId + " (" + (expectedMove.toString()) + ")");
          assert.isDefined(calculatedMoves[expectedMove], "Uncalculated move " + expectedMove + " from position " + positionString);
          if (depth === 1) {
            continue;
          }
          newDepth = depth - 1;
          counters = getInitialCounterArray(newDepth);
          testDepth(calculatedMoves[expectedMove].getNewPosition(), counters, 0, newDepth);
          calculatedQuantity = counters[newDepth - 1];
          _results1.push(assert.eql(calculatedQuantity, expectedQuantity, "Unexpected quantity for move " + expectedMove + " from position " + positionString + ": is " + calculatedQuantity + ", expected " + expectedQuantity));
        }
        return _results1;
      })());
    }
    return _results;
  },
  'test perftsuite.txt': function(beforeExit, assert) {
    var fs, iLine, nbLines, testFile, testLine;
    if (!DO_PERFTSUITE) {
      return;
    }
    fs = require('fs');
    nbLines = 0;
    iLine = 0;
    testLine = function(line) {
      var counter, counterId, counters, elems, expectedQuantity, maxDepth, positionObj, positionString, _i, _len;
      iLine++;
      elems = line.split(' ;');
      positionString = elems.shift();
      LOG_PERFTSUITE("Verifying line " + iLine + " of " + nbLines + " (" + positionString + "):");
      positionObj = positionClass.fromString(positionString);
      assert.eql(positionString, positionObj.toString());
      maxDepth = DEPTH;
      if (elems.length < maxDepth) {
        maxDepth = elem.length;
      }
      counters = getInitialCounterArray(maxDepth);
      testDepth(positionObj, counters, 0, maxDepth, LOG_PERFTSUITE);
      for (counterId = _i = 0, _len = counters.length; _i < _len; counterId = ++_i) {
        counter = counters[counterId];
        expectedQuantity = parseInt(elems[counterId].split(' ')[1]);
        assert.eql(counter, expectedQuantity);
      }
      LOG_PERFTSUITE("Position OK at depth " + maxDepth + ".");
      return LOG_PERFTSUITE("");
    };
    testFile = function(err, data) {
      var line, lineId, lines, _i, _len;
      if (err) {
        console.log(err);
        return;
      }
      lines = data.split("\n");
      for (lineId = _i = 0, _len = lines.length; _i < _len; lineId = ++_i) {
        line = lines[lineId];
        line = trimString(line);
        if (line === '') {
          lines.splice(lineId, 1);
        }
      }
      nbLines = lines.length;
      lines.map(testLine);
      return LOG_PERFTSUITE("All positions OK up to depth " + DEPTH + ".");
    };
    return fs.readFile('./test-data/perftsuite.txt', 'utf8', testFile);
  }
};
