###
Chess Move Generator
@author François Cardinaux, CH 1207 Genève
@copyright 2012 François Cardinaux

Licence: see README.md
###

# =============================================================================

class CMGBitBoard

    @EMPTY_BOARD    = [0, 0, 0, 0]
    @FULL_BOARD     = [0xffff, 0xffff, 0xffff, 0xffff]

    # Note:
    # @SQUARE_VALUES is generated by a metaprogram and placed at the END of this javascript

    # -------------------------------------------------------------------------
    # Bitboard maths (functions of class and of instance)

    @binEqual: (bb1, bb2) ->
        for quadrantId in [0..3]
            if bb1[quadrantId] isnt bb2[quadrantId]
                return false
        return true

    @binAnd: (bb1, bb2) ->
        [
            bb1[0] & bb2[0],
            bb1[1] & bb2[1],
            bb1[2] & bb2[2],
            bb1[3] & bb2[3]
        ]

    @binOr: (bb1, bb2) ->
        [
            bb1[0] | bb2[0],
            bb1[1] | bb2[1],
            bb1[2] | bb2[2],
            bb1[3] | bb2[3]
        ]

    @binXor: (bb1, bb2) ->
        [
            bb1[0] ^ bb2[0],
            bb1[1] ^ bb2[1],
            bb1[2] ^ bb2[2],
            bb1[3] ^ bb2[3]
        ]

    @binNot: (bb) ->
        [
            ~ bb[0],
            ~ bb[1],
            ~ bb[2],
            ~ bb[3]
        ]

    @valueOfSquare: (square) ->
        if typeof square is 'string'
            square = parseInt square
        @SQUARE_VALUES[square]

    @binLeftShift: (bb, n) ->
        res = []

        # Left shift (<< n) is limited to n < 32, so eliminate lost quadrants first
        while n >= 16
            # bb[3] is lost
            bb[3] = bb[2]
            bb[2] = bb[1]
            bb[1] = bb[0]
            bb[0] = 0
            n -= 16

        carry = 0
        for qKey in [0..3]
            shiftedBb = (bb[qKey] << n) + carry
            res[qKey] = shiftedBb & 0xffff
            carry = shiftedBb >> 16
        return res

    @bitBoardToSquareKeyArray: ( bitBoard ) ->
        squareKeys = []
        for quadrant, qid in bitBoard
            for key in [0..15]
                if (1 << key) & quadrant
                    squareKeys.push(qid * 16 + key)
        return squareKeys


# =============================================================================

class CMGPosition
    # -------------------------------------------------------------------------
    # Noticeable values:
    @ROW_SPAN:              8
    @BOTTOM_LEFT_CORNER:    0
    @BOTTOM_RIGHT_CORNER:   7
    @TOP_LEFT_CORNER:       070
    @TOP_RIGHT_CORNER:      077

    # -------------------------------------------------------------------------
    # Internal encoding for castling:
    @CASTLING_CODE_ALL:         15
    @CASTLING_CODE_WHITE_KING:   8
    @CASTLING_CODE_WHITE_QUEEN:  4
    @CASTLING_CODE_BLACK_KING:   2
    @CASTLING_CODE_BLACK_QUEEN:  1

    # -------------------------------------------------------------------------
    # Move bitboards
    # Note:
    # @QUEEN_MOVES, @ROOK_MOVES, @BISHOP_MOVES, @KNIGHT_MOVES,
    # @KING_MOVES_WITHOUT_CASTLING, @PAWN_NON_TAKING_MOVES, @PAWN_TAKING_MOVES
    # and @SHADOWS are generated by a metaprogram and placed at the END of this javascript

    @CASTLING_WHITE_KING:   { move: [ 64, 0, 0,     0 ], mustBeEmpty: [ 96, 0, 0,     0 ] } # Move = king position (  16) x 4
    @CASTLING_WHITE_QUEEN:  { move: [  4, 0, 0,     0 ], mustBeEmpty: [ 14, 0, 0,     0 ] } # Move = king position (  16) / 4
    @CASTLING_BLACK_KING:   { move: [  0, 0, 0, 16384 ], mustBeEmpty: [  0, 0, 0, 24576 ] } # Move = king position (4096) x 4
    @CASTLING_BLACK_QUEEN:  { move: [  0, 0, 0,  1024 ], mustBeEmpty: [  0, 0, 0,  3584 ] } # Move = king position (4096) / 4

    # -------------------------------------------------------------------------
    # Public functions of class (comparable to static methods)

    @fromString: (positionString) ->
        ###
        Get an object instance from its Forsyth-Edwards representation
        ###
        elements = positionString.split(' ')
        [boardString, turnChar, allowedCastlingString, enPassantString] = elements

        halfMoveClock = 0
        moveNumber = 1
        switch elements.length
            when 5
                halfMoveClock = parseInt(elements[4])
            when 6
                halfMoveClock = parseInt(elements[4])
                moveNumber = parseInt(elements[5])

        # Process each element one by one
        pieces            = CMGPosition._boardStringToPieces(boardString)
        allowedCastling   = CMGPosition._allowedCastlingStringToValue(allowedCastlingString)
        enPassantSquare   = CMGPosition._enPassantStringToSquare(enPassantString)
        turn              = CMGPosition._turnCharToValue(turnChar)

        # Return the position
        new CMGPosition(pieces, turn, allowedCastling, enPassantSquare, halfMoveClock, moveNumber)

    # -------------------------------------------------------------------------
    # Private functions of class (comparable to static methods)

    # Function to clone an object (http://keithdevens.com/weblog/archive/2007/Jun/07/javascript.clone)
    # @todo Move this function to an external library
    @_clone: (obj) ->
        if obj is null or typeof(obj) isnt 'object'
            return obj

        out = new obj.constructor()

        for key, value of obj
            out[key] = @_clone(value)

        out

    @_boardStringToPieces: (boardString) ->
        # Reverse, so that the table SquareTabId is immediately ordered by square ID
        rowStrings = boardString.split('/').reverse()
        CMGPosition._rowStringsToPieces(rowStrings)

    @_rowStringsToPieces: (rowStrings, pieces = [], rowId = 0) ->
        if rowStrings.length isnt 8
            throw "Incorrect number of rows in #{rowStrings}"

        pieces = {}

        for rowString, rowId in rowStrings
            pieces = CMGPosition._squareCharsToPieces(rowString.split(''), pieces, rowId * CMGPosition.ROW_SPAN, rowId * CMGPosition.ROW_SPAN + 7)

        return pieces

    @_squareCharsToPieces: (rowChars, pieces, currentSquareId, lastSquareIdOfRow) ->
        for rowChar in rowChars
            switch rowChar
                when '1' then currentSquareId += 1 # when character is '1'
                when '2' then currentSquareId += 2
                when '3' then currentSquareId += 3
                when '4' then currentSquareId += 4
                when '5' then currentSquareId += 5
                when '6' then currentSquareId += 6
                when '7' then currentSquareId += 7
                when '8' then currentSquareId += 8 # when character is '8'
                else
                    pieces[currentSquareId] = CMGPiece.fromChar( rowChar )
                    currentSquareId += 1

        return pieces

    @_allowedCastlingStringToValue: (allowedCastlingString) ->
        if allowedCastlingString is '-'
            return 0

        func = (acc, pce) ->
            switch pce
                when 'K' then return acc + CMGPosition.CASTLING_CODE_WHITE_KING
                when 'Q' then return acc + CMGPosition.CASTLING_CODE_WHITE_QUEEN
                when 'k' then return acc + CMGPosition.CASTLING_CODE_BLACK_KING
                when 'q' then return acc + CMGPosition.CASTLING_CODE_BLACK_QUEEN
            acc

        allowedCastlingString.split('').reduce(func, 0)

    @_allowedCastlingValueToString: (allowedCastling) ->
        if allowedCastling is 0
            return '-'

        wqChar = wkChar = bqChar = bkChar = ''
        wqChar = 'Q' if allowedCastling & CMGPosition.CASTLING_CODE_WHITE_QUEEN
        wkChar = 'K' if allowedCastling & CMGPosition.CASTLING_CODE_WHITE_KING
        bqChar = 'q' if allowedCastling & CMGPosition.CASTLING_CODE_BLACK_QUEEN
        bkChar = 'k' if allowedCastling & CMGPosition.CASTLING_CODE_BLACK_KING

        allowedCastlingString = [wkChar, wqChar, bkChar, bqChar].join('')

        return allowedCastlingString

    @_enPassantStringToSquare: (enPassantString) ->
        if enPassantString is '-'
            return false

        if enPassantString.length isnt 2
            throw "Invalid en-passant string: #{enPassantString}"
        colValue = enPassantString.charCodeAt(0) - 97 # 'a' in ascii
        rowValue = enPassantString.charCodeAt(1) - 49 # '1' in ascii
        CMGPosition._squareReference(rowValue, colValue)

    @_turnCharToValue: (turnChar) ->
        if turnChar isnt 'b' and turnChar isnt 'w'
            throw "Invalid turn character: #{turnChar}"

        return turnChar

    @_squareReference: (rowId, colId) ->
        CMGPosition.ROW_SPAN * rowId + colId

    @_getPieceOnSquare: (item, squareKey) ->
        pieces = null
        if item instanceof CMGPosition
            pieces = item.pieces
        else
            pieces = item

        if not pieces.hasOwnProperty(squareKey)
            return false

        return pieces[squareKey]

    @_shadow: (square, direction) ->
        # @param direction (int): 0 = north, 1 = north-east, ..., 7 = north-west (i.e. clockwise)
        @SHADOWS[square][direction]

    @_light: (square, direction) ->
        # @param direction (int): 0 = north, 1 = north-east, ..., 7 = north-west (i.e. clockwise)
        @SHADOWS[square][direction ^ 4] # ^ = xor

    @_oppositeColor: (color, defaultValue = false) ->
        switch color
            when "b" then return "w"
            when "w" then return "b"
        defaultValue

    # -------------------------------------------------------------------------
    # Constructor

    constructor: (@pieces, @turn, @allowedCastling = 0, @enPassantSquare = false, @halfMoveClock = 0, @moveNumber = 0) ->
        ###
        Constructor
        @param pieces (Object) With object keys = square ids and object values = instances of CMGPiece
        @param turn (false|"b"|"w")
        @param allowedCastling (integer)
        @param enPassantSquare (false|integer where integer is between 0 (bottom right corner) and 077 (top right corner)
        @param halfMoveClock (integer)
        @param moveNumber (integer)
        ###

        @bitBoards = {}
        @_generateBitBoards()

        # Load pieces of color
        @piecesOfColor = {b: {}, w: {}}
        if @pieces
            # This test is necessary, because if _clone() is used, the object is first created empty
            for squareId, piece of @pieces
                @piecesOfColor[piece.color][squareId] = piece


    # -------------------------------------------------------------------------
    # Public functions of object (comparable to non static methods)

    playerColorCode: () ->
        @turn

    opponentColorCode: () ->
        CMGPosition._oppositeColor(@turn)

    toString: () ->
        ###
        Get the Forsyth-Edwards representation of the object
        ###
        [@toStringWithoutCounters(), @halfMoveClock, @moveNumber].join(' ')

    toStringWithoutCounters: () ->
        boardString = @_piecesToBoardString(@pieces)
        turnChar = @turn # neither filtering nor transformation necessary in this direction
        allowedCastlingString = CMGPosition._allowedCastlingValueToString(@allowedCastling)
        enPassantString = @_enPassantSquareToString(@enPassantSquare)

        [boardString, turnChar, allowedCastlingString, enPassantString].join(' ')

    isValidMove: (fromSquare, toSquare, promotion = false) ->
        # todo implement... with @_isValidMoveObject()?
        true

    allPossibleMovesFromSquare: (squareKey) ->

        piece = @_getPieceOnSquare(squareKey)
        if not piece
            return 0x0

        if piece.color isnt @turn
            return 0x0

        # First, seach all "ordinary" pseudo moves
        pseudoMoveBitboard = @_bitBoardOfPseudoMovesFromSquare(squareKey, piece, @turn)

        # Second, convert the move bitboard into a move array, and execute promotion if required
        pseudoMoves = []
        targets = CMGBitBoard.bitBoardToSquareKeyArray( pseudoMoveBitboard )
        for target in targets
            toPiece = piece
            takenPiece = @_getPieceOnSquare(target)
            if takenPiece
                takenOnSquare = target
            if piece.type is 'p' and (target >= CMGPosition.TOP_LEFT_CORNER or target <= CMGPosition.BOTTOM_RIGHT_CORNER)
                # A promotion
                for newPieceType in ['q', 'r', 'n', 'b']
                    move = new CMGMove(squareKey, piece, target, newPieceType, null, false, takenPiece, takenOnSquare)
                    move.setNewPositionObject( @_getNewPositionObjectAfterMove(move) )
                    pseudoMoves.push(move)
            else
                move = new CMGMove(squareKey, piece, target, toPiece, null, false, takenPiece, takenOnSquare)
                move.setNewPositionObject( @_getNewPositionObjectAfterMove(move) )
                pseudoMoves.push(move)

        # Finally, eliminate invalid moves:
        out = []

        for pseudoMove in pseudoMoves
            if @_isValidMoveObject(pseudoMove)
                out.push(pseudoMove)

        return out

    _getNewPositionObjectAfterMove: (move) ->
        pieces = CMGPosition._clone( @pieces )

        pieces[move.fromSquare] = null # ensure garbage collection
        delete pieces[move.fromSquare] # remove the element from the object

        if move.takenOnSquare
            pieces[move.takenOnSquare] = null # ensure garbage collection
            delete pieces[move.takenOnSquare] # remove the element from the object

        pieces[move.toSquare] = move.toPiece

        # Move the rook if castling
        if move.castling is 'k'
            if @turn is 'b'
                pieces[075] = pieces[077]
                delete pieces[077]
            if @turn is 'w'
                pieces[5] = pieces[7]
                delete pieces[7]
        else if move.castling is 'q'
            if @turn is 'b'
                pieces[072] = pieces[070]
                delete pieces[070]
            if @turn is 'w'
                pieces[2] = pieces[0]
                delete pieces[0]

        turn = @opponentColorCode()

        # Determine new 'allowed castling' value
        allowedCastling = @allowedCastling
        switch move.fromSquare
            when   0 then allowedCastling &= ( ~ CMGPosition.CASTLING_CODE_WHITE_QUEEN )
            when   4 then allowedCastling &= ( ~ CMGPosition.CASTLING_CODE_WHITE_QUEEN & ~ CMGPosition.CASTLING_CODE_WHITE_KING )
            when   7 then allowedCastling &= ( ~ CMGPosition.CASTLING_CODE_WHITE_KING )
            when 070 then allowedCastling &= ( ~ CMGPosition.CASTLING_CODE_BLACK_QUEEN )
            when 074 then allowedCastling &= ( ~ CMGPosition.CASTLING_CODE_BLACK_QUEEN & ~ CMGPosition.CASTLING_CODE_BLACK_KING )
            when 077 then allowedCastling &= ( ~ CMGPosition.CASTLING_CODE_BLACK_KING )

        enPassantSquare = false # todo

        halfMoveClock   = @halfMoveClock
        moveNumber      = @moveNumber
        if moveNumber > 0
            # With counters
            halfMoveClock += 1
            if turn is 'w'
                moveNumber += 1

        new CMGPosition(pieces, turn, allowedCastling, enPassantSquare, halfMoveClock, moveNumber)

    allPossibleMoves: () ->
        result = []

        for square, piece of @pieces
            if piece.color isnt @turn
                continue
            moves = @allPossibleMovesFromSquare(square)
            if moves.length > 0
                result = result.concat(moves)

        return result

    isDraw: () ->
        ###
        Is the position a draw
        @return boolean
        ###
        return 'todo'

    getWinnerColorCode: () ->
        ###
        Get the winner color code
        @return (false|'b'|'w')
        ###
        return 'todo'

    # -------------------------------------------------------------------------
    # Private functions of object (comparable to non static methods)

    _bitBoardOfPseudoMoves: (stopAtColor = false, stopAfterColor = false) ->
        out = CMGBitBoard.EMPTY_BOARD
        for pieceSquare, piece of @piecesOfColor[@turn]
            out = CMGBitBoard.binOr( out, @_bitBoardOfPseudoMovesFromSquare(pieceSquare, piece, stopAtColor, stopAfterColor) )

        return out

    _bitBoardOfPseudoMovesFromSquare: (squareKey, movedPiece, stopAtColor = false, stopAfterColor = false) ->
        out = CMGBitBoard.EMPTY_BOARD

        if not movedPiece
            return CMGBitBoard.EMPTY_BOARD

        switch movedPiece.type
            when 'r'
                shadows = @_computeShadows(squareKey, [0, 2, 4, 6], stopAtColor, stopAfterColor)
                out = CMGBitBoard.binAnd( CMGPosition.ROOK_MOVES[squareKey], CMGBitBoard.binNot(shadows) )
            when 'n'
                out = CMGBitBoard.binAnd( CMGPosition.KNIGHT_MOVES[squareKey], CMGBitBoard.binNot(@bitBoards.allPiecesOfColor[@turn]) )
            when 'b'
                shadows = @_computeShadows(squareKey, [1, 3, 5, 7], stopAtColor, stopAfterColor)
                out = CMGBitBoard.binAnd( CMGPosition.BISHOP_MOVES[squareKey], CMGBitBoard.binNot(shadows) )
            when 'q'
                shadows = @_computeShadows(squareKey, [0..7], stopAtColor, stopAfterColor)
                out = CMGBitBoard.binAnd( CMGPosition.QUEEN_MOVES[squareKey], CMGBitBoard.binNot(shadows) )
            when 'k'
                shadows = @_computeShadows(squareKey, [0..7], stopAtColor, stopAfterColor)
                out = CMGBitBoard.binAnd( CMGPosition.KING_MOVES_WITHOUT_CASTLING[squareKey], CMGBitBoard.binNot(shadows) )

                # Castling move if any
                if movedPiece.color is 'b'
                    if      (@allowedCastling & CMGPosition.CASTLING_CODE_BLACK_KING)  and CMGBitBoard.isZero( CMGBitBoard.binAnd( @bitBoards.allPieces, CMGPosition.CASTLING_BLACK_KING.mustBeEmpty ) )
                        out = CMGBitBoard.binOr( out, CMGPosition.CASTLING_BLACK_KING.move )
                    else if (@allowedCastling & CMGPosition.CASTLING_CODE_BLACK_QUEEN) and CMGBitBoard.isZero( CMGBitBoard.binAnd( @bitBoards.allPieces, CMGPosition.CASTLING_BLACK_QUEEN.mustBeEmpty ) )
                        out = CMGBitBoard.binOr( out, CMGPosition.CASTLING_BLACK_QUEEN.move )
                else
                    if      (@allowedCastling & CMGPosition.CASTLING_CODE_WHITE_KING)  and CMGBitBoard.isZero( CMGBitBoard.binAnd( @bitBoards.allPieces, CMGPosition.CASTLING_WHITE_KING.mustBeEmpty ) )
                        out = CMGBitBoard.binOr( out, CMGPosition.CASTLING_WHITE_KING.move )
                    else if (@allowedCastling & CMGPosition.CASTLING_CODE_WHITE_QUEEN) and CMGBitBoard.isZero( CMGBitBoard.binAnd( @bitBoards.allPieces, CMGPosition.CASTLING_WHITE_QUEEN.mustBeEmpty ) )
                        out = CMGBitBoard.binOr( out, CMGPosition.CASTLING_WHITE_QUEEN.move )

            when 'p'
                shadowDirections = [0] if stopAtColor is 'w'
                shadowDirections = [4] if stopAtColor is 'b'
                allShadows = @_computeShadows(squareKey, shadowDirections, '*')
                nonTakingMoves = CMGBitBoard.binAnd( CMGPosition.PAWN_NON_TAKING_MOVES[squareKey], CMGBitBoard.binNot(allShadows) )
                out = CMGBitBoard.binOr( CMGPosition.PAWN_TAKING_MOVES[squareKey], nonTakingMoves )

        return out

    _computeShadows: (squareKey, directions, stopAtColor = '*', stopAfterColor = false) ->

        shadowMap = CMGBitBoard.EMPTY_BOARD

        if stopAtColor
            shadowMap = CMGBitBoard.binOr( shadowMap, @_computeSingleBehaviorShadows(squareKey, directions, stopAtColor, false) )

        if stopAfterColor
            shadowMap = CMGBitBoard.binOr( shadowMap, @_computeSingleBehaviorShadows(squareKey, directions, stopAfterColor, true) )

        return shadowMap

    _computeSingleBehaviorShadows: (squareKey, directions, stoppingColor = '*', stopAfterOnly = false) ->
        shadowMap = CMGBitBoard.EMPTY_BOARD

        pieces = null
        if stoppingColor is '*'
            pieces = @pieces
        else
            pieces = @piecesOfColor[stoppingColor]

        squareKeyBitBoard = CMGBitBoard.valueOfSquare(squareKey)

        for pieceSquare, piece of pieces
            if pieceSquare is squareKey
                continue # skip the light origin itself

            pieceSquareBitBoard = CMGBitBoard.valueOfSquare(pieceSquare)

            exclusionMap = false
            if stopAfterOnly
                exclusionMap = CMGBitBoard.binNot( pieceSquareBitBoard )

            for direction in directions
                if CMGBitBoard.binAnd( CMGPosition._light(pieceSquare, direction), squareKeyBitBoard )
                    shadowMap = CMGBitBoard.binOr( shadowMap, CMGPosition._shadow(pieceSquare, direction) )
                    if exclusionMap
                        shadowMap = CMGBitBoard.binAnd( shadowMap, exclusionMap )
                    break # correct direction found, break 1 level
        return shadowMap

    _isValidMoveObject: (move) ->
        ###
        Is the pseudo move a valid move:
        * pawn taking moves where nothing can be taken (verify also en passant)
        * move after which the king is under chess
        * castling moves that cross a threatened square
        ###

        if move.fromPiece.type is 'p' and ( Math.abs(move.toSquare - move.fromSquare) % 8 ) isnt 0 and move.takenPiece is false
            # A taking move with a pawn, but no piece has been taken
            return false

        pseudoThreatsOnPlayerAfterMove = move.newPosition._bitBoardOfPseudoMoves(@opponentColorCode(), @turn)

        kingBitBoard = move.newPosition.bitBoards.allPiecesOfColorAndType[@turn]['k']

        kingAttackBitBoard = CMGBitBoard.binAnd( kingBitBoard, pseudoThreatsOnPlayerAfterMove )

        if not CMGBitBoard.binEqual(kingAttackBitBoard, CMGBitBoard.EMPTY_BOARD)
            return false

        # promotion = false
        # if move.toPiece isnt move.fromPiece
        #     promotion = move.toPiece
        # @isValidMove(move.fromSquare, move.toSquare, promotion)

        return true

    _piecesToBoardString: () ->
        ( @_piecesToRowStrings() ).join('/')

    _piecesToRowStrings: () ->
        rowId = 8
        rowStrings = []

        while rowId > 0
            rowId--
            rowStrings.push( @_piecesOnRowToRowString(rowId) )

        return rowStrings

    _piecesOnRowToRowString: (rowId) ->
        colId = 0
        rowChars = []
        emptySquareCounter = 0

        while colId < 8

            squareKey = CMGPosition._squareReference(rowId, colId)
            pieceFound = @_getPieceOnSquare(squareKey)

            if pieceFound is false
                emptySquareCounter++
            else
                pieceChar = pieceFound.toChar()
                if emptySquareCounter > 0
                    rowChars.push(emptySquareCounter)
                rowChars.push(pieceChar)
                emptySquareCounter = 0

            colId++

        if emptySquareCounter isnt 0
            rowChars.push(emptySquareCounter)

        rowChars.join('')

    _enPassantSquareToString: (squareNumber) ->
        if squareNumber is false
            return '-'

        return @_squareToString(squareNumber)

    _squareToString: (squareNumber) ->
        rowValue = Math.floor(squareNumber / CMGPosition.ROW_SPAN)
        colValue = squareNumber % CMGPosition.ROW_SPAN

        String.fromCharCode(colValue + 97) + String.fromCharCode(rowValue + 49) # 97 is 'a', 49 is '1'

    _getPieceOnSquare: (squareKey) ->
        CMGPosition._getPieceOnSquare(@pieces, squareKey)

    _generateBitBoards: () ->
        @bitBoards.allPieces = CMGBitBoard.EMPTY_BOARD
        @bitBoards.allPiecesOfColor =
            'b': CMGBitBoard.EMPTY_BOARD
            'w': CMGBitBoard.EMPTY_BOARD
        @bitBoards.allPiecesOfColorAndType =
            'b':
                'r': CMGBitBoard.EMPTY_BOARD
                'n': CMGBitBoard.EMPTY_BOARD
                'b': CMGBitBoard.EMPTY_BOARD
                'k': CMGBitBoard.EMPTY_BOARD
                'q': CMGBitBoard.EMPTY_BOARD
                'p': CMGBitBoard.EMPTY_BOARD
            'w':
                'r': CMGBitBoard.EMPTY_BOARD
                'n': CMGBitBoard.EMPTY_BOARD
                'b': CMGBitBoard.EMPTY_BOARD
                'k': CMGBitBoard.EMPTY_BOARD
                'q': CMGBitBoard.EMPTY_BOARD
                'p': CMGBitBoard.EMPTY_BOARD

        for square, {color: color, type: type} of @pieces
            bvs = CMGBitBoard.valueOfSquare(square)
            @bitBoards.allPieces                            = CMGBitBoard.binOr(bvs, @bitBoards.allPieces)
            @bitBoards.allPiecesOfColor[color]              = CMGBitBoard.binOr(bvs, @bitBoards.allPiecesOfColor[color])
            @bitBoards.allPiecesOfColorAndType[color][type] = CMGBitBoard.binOr(bvs, @bitBoards.allPiecesOfColorAndType[color][type])

# =============================================================================

class CMGMove
    constructor: (@fromSquare, @fromPiece, @toSquare, @toPiece, @newPosition, @castling = false, @takenPiece = false, @takenOnSquare = false) ->
        ###
        Constructor
        @param fromSquare (integer)
        @param fromPiece (CMGPiece)
        @param toSquare (integer)
        @param toPiece (CMGPiece)
        @param newPosition (CMGPosition)
        @param castling (false|"q"|"k")
        @param takenPiece (false|CMGPiece)
        @param takenOnSquare (false|integer)
        ###

    toString:   () ->
        CMGPosition._squareToString(fromSquare) + CMGPosition._squareToString(toSquare)

    setNewPositionObject: (@newPosition) ->

# =============================================================================

class CMGPiece
    constructor: (@color, @type) ->
        ###
        Constructor
        @param color ("b"|"w") black or white
        @param type ("p"|"n"|b"|"r"|"q"|"k") pawn, knight, bishop, rook, queen or king
        ###

    # -------------------------------------------------------------------------
    # Public functions of class (comparable to static methods)

    @fromChar: (pieceChar) ->
        [color, piece] = CMGPiece._charToInternalRepresentation( pieceChar )

        return new CMGPiece( color, piece )

    # -------------------------------------------------------------------------
    # Protected functions of class (comparable to static methods)

    @_charToInternalRepresentation: (pieceChar) ->
        charCode = pieceChar.charCodeAt(0)
        color = 'b'
        piece = null
        if charCode < 97
            # Uppercase => transform and mark as white
            color = 'w'
            charCode += 32 # 97 - 65, i.e. code('a') - code('A')

        if charCode isnt 114 and charCode isnt 110 and charCode isnt 98 and charCode isnt 113 and charCode isnt 107 and charCode isnt 112
            # Not in r, n, b, q, k, p
            throw "Invalid character code to represent a chess piece: #{charCode}"

        return [color, String.fromCharCode(charCode)]

    # -------------------------------------------------------------------------
    # Public functions of object (comparable to non-static methods)

    toChar: () ->
        out = @type

        if @color is 'w'
            out = String.fromCharCode( @type.charCodeAt(0) - 32 ) # 97 - 65, i.e. code('a') - code('A')

        return out


# =============================================================================

module.exports =
    bitBoard: CMGBitBoard
    position: CMGPosition
    move: CMGMove
