###
Chess Move Generator
@author François Cardinaux, CH 1207 Genève
@copyright 2012 François Cardinaux

Licence: see README.md
###

# =============================================================================

class CMGPosition
    # Noticeable values:
    @ROW_SPAN:              8
    @BOTTOM_LEFT_CORNER:    0
    @BOTTOM_RIGHT_CORNER:   7
    @TOP_LEFT_CORNER:       070
    @TOP_RIGHT_CORNER:      077

    # Internal encoding for castling:
    @CASTLING_ALL:         15
    @CASTLING_WHITE_KING:   8
    @CASTLING_WHITE_QUEEN:  4
    @CASTLING_BLACK_KING:   2
    @CASTLING_BLACK_QUEEN:  1

    # Note:
    # @QUEEN_MOVES, @ROOK_MOVES, @BISHOP_MOVES, @KNIGHT_MOVES,
    # @KING_MOVES_WITHOUT_CASTLING, @PAWN_NON_TAKING_MOVES, @PAWN_TAKING_MOVES
    # and @SHADOWS are generated by a metaprogram and placed at the END of this javascript

    # -------------------------------------------------------------------------
    # Public functions of class (comparable to static methods)

    @fromString: (positionString) ->
        ###
        Get an object instance from its Forsyth-Edwards representation
        ###
        elements = positionString.split(' ')
        [boardString, turnChar, allowedCastlingString, enPassantString] = elements

        halfMoveClock = 0
        moveNumber = 1
        switch elements.length
            when 5
                halfMoveClock = parseInt(elements[4])
            when 6
                halfMoveClock = parseInt(elements[4])
                moveNumber = parseInt(elements[5])

        # Process each element one by one
        pieces            = CMGPosition._boardStringToPieces(boardString)
        allowedCastling   = CMGPosition._allowedCastlingStringToValue(allowedCastlingString)
        enPassantSquare   = CMGPosition._enPassantStringToSquare(enPassantString)
        turn              = CMGPosition._turnCharToValue(turnChar)

        # Return the position
        new CMGPosition(pieces, turn, allowedCastling, enPassantSquare, halfMoveClock, moveNumber)

    # -------------------------------------------------------------------------
    # Private functions of class (comparable to static methods)

    @_boardStringToPieces: (boardString) ->
        # Reverse, so that the table SquareTabId is immediately ordered by square ID
        rowStrings = boardString.split('/').reverse()
        CMGPosition._rowStringsToPieces(rowStrings)

    @_rowStringsToPieces: (rowStrings, pieces = [], rowId = 0) ->
        if rowStrings.length isnt 8
            throw "Incorrect number of rows in #{rowStrings}"

        pieces = {}

        for rowString, rowId in rowStrings
            pieces = CMGPosition._squareCharsToPieces(rowString.split(''), pieces, rowId * CMGPosition.ROW_SPAN, rowId * CMGPosition.ROW_SPAN + 7)

        return pieces

    @_squareCharsToPieces: (rowChars, pieces, currentSquareId, lastSquareIdOfRow) ->
        for rowChar in rowChars
            switch rowChar
                when '1' then currentSquareId += 1 # when character is '1'
                when '2' then currentSquareId += 2
                when '3' then currentSquareId += 3
                when '4' then currentSquareId += 4
                when '5' then currentSquareId += 5
                when '6' then currentSquareId += 6
                when '7' then currentSquareId += 7
                when '8' then currentSquareId += 8 # when character is '8'
                else
                    pieces[currentSquareId] = CMGPiece.fromChar( rowChar )
                    currentSquareId += 1

        return pieces

    @_allowedCastlingStringToValue: (allowedCastlingString) ->
        func = (acc, pce) ->
            switch pce
                when 'K' then return acc + CMGPosition.CASTLING_WHITE_KING
                when 'Q' then return acc + CMGPosition.CASTLING_WHITE_QUEEN
                when 'k' then return acc + CMGPosition.CASTLING_BLACK_KING
                when 'q' then return acc + CMGPosition.CASTLING_BLACK_QUEEN
            acc

        allowedCastlingString.split('').reduce(func, 0)

    @_allowedCastlingValueToString: (allowedCastling) ->
        wqChar = wkChar = bqChar = bkChar = ''
        wqChar = 'Q' if allowedCastling & CMGPosition.CASTLING_WHITE_QUEEN
        wkChar = 'K' if allowedCastling & CMGPosition.CASTLING_WHITE_KING
        bqChar = 'q' if allowedCastling & CMGPosition.CASTLING_BLACK_QUEEN
        bkChar = 'k' if allowedCastling & CMGPosition.CASTLING_BLACK_KING

        allowedCastlingString = [wkChar, wqChar, bkChar, bqChar].join('')
        if allowedCastlingString is ''
            return '-'

        return allowedCastlingString

    @_enPassantStringToSquare: (enPassantString) ->
        if enPassantString is '-'
            return false

        if enPassantString.length isnt 2
            throw "Invalid en-passant string: #{enPassantString}"
        colValue = enPassantString.charCodeAt(0) - 97 # 'a' in ascii
        rowValue = enPassantString.charCodeAt(1) - 49 # '1' in ascii
        CMGPosition._squareReference(rowValue, colValue)

    @_turnCharToValue: (turnChar) ->
        if turnChar isnt 'b' and turnChar isnt 'w'
            throw "Invalid turn character: #{turnChar}"

        return turnChar

    @_squareReference: (rowId, colId) ->
        CMGPosition.ROW_SPAN * rowId + colId

    @_getPieceOnSquare: (item, squareKey) ->
        pieces = null
        if item instanceof CMGPosition
            pieces = item.pieces
        else
            pieces = item

        if not pieces.hasOwnProperty(squareKey)
            return false

        return pieces[squareKey]

    @_shadow: (square, direction) ->
        # @param direction (int): 0 = north, 1 = north-east, ..., 7 = north-west (i.e. clockwise)
        @SHADOWS[square][direction]

    @_light: (square, direction) ->
        # @param direction (int): 0 = north, 1 = north-east, ..., 7 = north-west (i.e. clockwise)
        @SHADOWS[square][direction ^ 4] # ^ = xor

    # -------------------------------------------------------------------------
    # Constructor

    constructor: (@pieces, @turn, @allowedCastling = 0, @enPassantSquare = false, @halfMoveClock = 0, @moveNumber = 0) ->
        ###
        Constructor
        @param pieces ([CMGPiece])
        @param turn (false|"b"|"w")
        @param allowedCastling (integer)
        @param enPassantSquare (false|integer where integer is between 0 (bottom right corner) and 077 (top right corner)
        @param halfMoveClock (integer)
        @param moveNumber (integer)
        ###

        @bitBoards = {}
        @_generateBitBoards()

        # Load pieces of color
        @piecesOfColor = {b: [], w: []}
        for piece in @pieces
            @piecesOfColor[piece.color].push(piece)


    # -------------------------------------------------------------------------
    # Public functions of object (comparable to non static methods)

    playerColorCode: () ->
        @turn

    opponentColorCode: () ->
        switch @turn
            when "b" then return "w"
            when "w" then return "b"
        false

    toString: () ->
        ###
        Get the Forsyth-Edwards representation of the object
        ###
        [@toStringWithoutCounters(), @halfMoveClock, @moveNumber].join(' ')

    toStringWithoutCounters: () ->
        boardString = @_piecesToBoardString(@pieces)
        turnChar = @turn # neither filtering nor transformation necessary in this direction
        allowedCastlingString = CMGPosition._allowedCastlingValueToString(@allowedCastling)
        enPassantString = @_enPassantSquareToString(@enPassantSquare)

        [boardString, turnChar, allowedCastlingString, enPassantString].join(' ')

    isValidMove: (fromSquare, toSquare, promotion = false) ->
        # todo implement... with @_isValidMoveObject()?
        true

    allPossibleMovesFromSquare: (squareKey) ->
        # First, seach all pseudo moves
        pseudoMoves = []

        piece = @_getPieceOnSquare(squareKey)
        if not piece
            return []

        if piece.color isnt @turn
            return []

        switch piece.type
            when 'r'
                shadows = @_computeShadows(squareKey, [0, 2, 4, 6], @turn)
                pseudoMoves = CMGPosition.ROOK_MOVES[squareKey] & ~ shadows
            when 'n'
                pseudoMoves = CMGPosition.KNIGHT_MOVES[squareKey] & ~ @bitBoards.allPiecesOfColor[@turn]
            when 'b'
                shadows = @_computeShadows(squareKey, [1, 3, 5, 7], @turn)
                pseudoMoves = CMGPosition.BISHOP_MOVES[squareKey] & ~ shadows
            when 'q'
                shadows = @_computeShadows(squareKey, [0..7], @turn)
                pseudoMoves = CMGPosition.QUEEN_MOVES[squareKey] & ~ shadows
            when 'k'
                shadows = @_computeShadows(squareKey, [0..7], @turn)
                pseudoMoves = CMGPosition.KING_MOVES_WITHOUT_CASTLING[squareKey] & ~ shadows
            when 'p'
                shadowDirections = [0] if @turn is 'w'
                shadowDirections = [4] if @turn is 'b'
                shadows = @_computeShadows(squareKey, shadowDirections, @turn)
                nonTakingMoves = CMGPosition.PAWN_NON_TAKING_MOVES[squareKey] & ~ shadows

                pseudoMoves = CMGPosition.PAWN_TAKING_MOVES[squareKey].concat(nonTakingMoves)

        # Next, eliminate invalid moves
        out = []

        for pseudoMove in pseudoMoves
            if @_isValidMoveObject(pseudoMove)
                out.push(pseudoMove)

        return out

    allPossibleMoves: () ->
        result = []

        for square, piece of @pieces
            if piece.color isnt @turn
                continue
            moves = @allPossibleMovesFromSquare(square)
            if moves.length > 0
                result = result.concat(moves)

        return result

    isDraw: () ->
        ###
        Is the position a draw
        @return boolean
        ###
        return 'todo'

    getWinnerColorCode: () ->
        ###
        Get the winner color code
        @return (false|'b'|'w')
        ###
        return 'todo'

    # -------------------------------------------------------------------------
    # Bitboard maths

    _binAnd: (bb1, bb2) ->
        [
            bb1[0] & bb2[0],
            bb1[1] & bb2[1],
            bb1[2] & bb2[2],
            bb1[3] & bb2[3]
        ]

    _binOr: (bb1, bb2) ->
        [
            bb1[0] | bb2[0],
            bb1[1] | bb2[1],
            bb1[2] | bb2[2],
            bb1[3] | bb2[3]
        ]

    _binXor: (bb1, bb2) ->
        [
            bb1[0] ^ bb2[0],
            bb1[1] ^ bb2[1],
            bb1[2] ^ bb2[2],
            bb1[3] ^ bb2[3]
        ]

    _binNot: (bb) ->
        [
            ~ bb[0],
            ~ bb[1],
            ~ bb[2],
            ~ bb[3]
        ]
    _binLeftShift: (bb, n) ->
        res = []

    # -------------------------------------------------------------------------
    # Private functions of object (comparable to non static methods)

    _computeShadows: (squareKey, directions, pieceColorFilter) ->
        shadowMap = [0x0, 0x0, 0x0, 0x0]
        for playerPiece in @piecesOfColor[@turn]
            if CMGPosition._light(playerPiece.square) & @_bitValueOfSquare(squareKey)
            playerPiece.

        CMGPosition.SHADOWS todo

    _isValidMoveObject: (move) ->
        promotion = false
        if move.toPiece isnt move.fromPiece
            promotion = move.toPiece

        @isValidMove(move.fromSquare, move.toSquare, promotion)

    _piecesToBoardString: () ->
        ( @_piecesToRowStrings() ).join('/')

    _piecesToRowStrings: () ->
        rowId = 8
        rowStrings = []

        while rowId > 0
            rowId--
            rowStrings.push( @_piecesOnRowToRowString(rowId) )

        return rowStrings

    _piecesOnRowToRowString: (rowId) ->
        colId = 0
        rowChars = []
        emptySquareCounter = 0

        while colId < 8

            squareKey = CMGPosition._squareReference(rowId, colId)
            pieceFound = @_getPieceOnSquare(squareKey)

            if pieceFound is false
                emptySquareCounter++
            else
                pieceChar = pieceFound.toChar()
                if emptySquareCounter > 0
                    rowChars.push(emptySquareCounter)
                rowChars.push(pieceChar)
                emptySquareCounter = 0

            colId++

        if emptySquareCounter isnt 0
            rowChars.push(emptySquareCounter)

        rowChars.join('')

    _enPassantSquareToString: (squareNumber) ->
        if squareNumber is false
            return '-'

        return @_squareToString(squareNumber)

    _squareToString: (squareNumber) ->
        rowValue = Math.floor(squareNumber / CMGPosition.ROW_SPAN)
        colValue = squareNumber % CMGPosition.ROW_SPAN

        String.fromCharCode(colValue + 97) + String.fromCharCode(rowValue + 49) # 97 is 'a', 49 is '1'

    _getPieceOnSquare: (squareKey) ->
        CMGPosition._getPieceOnSquare(@pieces, squareKey)

    _generateBitBoards: () ->
        @bitBoards.allPieces = 0x0
        @bitBoards.allPiecesOfColor = 0x0
        @bitBoards.allPiecesOfColorAndType =
            'b':
                'r': 0x0
                'n': 0x0
                'b': 0x0
                'k': 0x0
                'q': 0x0
                'p': 0x0
            'w':
                'r': 0x0
                'n': 0x0
                'b': 0x0
                'k': 0x0
                'q': 0x0
                'p': 0x0

        for square, {color: color, type: type} of @pieces
            bvs = @_bitValueOfSquare(square)
            @bitBoards.allPieces |= bvs
            @bitBoards.allPiecesOfColor[color] |= bvs
            @bitBoards.allPiecesOfColorAndType[color][type] |= bvs

    _bitValueOfSquare: (square) ->
        return 1 << square

# =============================================================================

class CMGMove
    constructor: (@fromSquare, @fromPiece, @toSquare, @toPiece, @newPosition, @castling = false, @takenPiece = false, @takenOnSquare = false) ->
        ###
        Constructor
        @param fromSquare (integer)
        @param fromPiece (CMGPiece)
        @param toSquare (integer)
        @param toPiece (CMGPiece)
        @param newPosition (CMGPosition)
        @param castling (false|"q"|"k")
        @param takenPiece (false|CMGPiece)
        @param takenOnSquare (false|integer)
        ###

    toString:   () ->
        CMGPosition._squareToString(fromSquare) + CMGPosition._squareToString(toSquare)



# =============================================================================

class CMGPiece
    constructor: (@color, @type) ->
        ###
        Constructor
        @param color ("b"|"w") black or white
        @param type ("p"|"n"|b"|"r"|"q"|"k") pawn, knight, bishop, rook, queen or king
        ###

    # -------------------------------------------------------------------------
    # Public functions of class (comparable to static methods)

    @fromChar: (pieceChar) ->
        [color, piece] = CMGPiece._charToInternalRepresentation( pieceChar )

        return new CMGPiece( color, piece )

    # -------------------------------------------------------------------------
    # Protected functions of class (comparable to static methods)

    @_charToInternalRepresentation: (pieceChar) ->
        charCode = pieceChar.charCodeAt(0)
        color = 'b'
        piece = null
        if charCode < 97
            # Uppercase => transform and mark as white
            color = 'w'
            charCode += 32 # 97 - 65, i.e. code('a') - code('A')

        if charCode isnt 114 and charCode isnt 110 and charCode isnt 98 and charCode isnt 113 and charCode isnt 107 and charCode isnt 112
            # Not in r, n, b, q, k, p
            throw "Invalid character code to represent a chess piece: #{charCode}"

        return [color, String.fromCharCode(charCode)]

    # -------------------------------------------------------------------------
    # Public functions of object (comparable to non-static methods)

    toChar: () ->
        out = @type

        if @color is 'w'
            out = String.fromCharCode( @type.charCodeAt(0) - 32 ) # 97 - 65, i.e. code('a') - code('A')

        return out


# =============================================================================

module.exports =
    position: CMGPosition
    move: CMGMove
