###
Chess Move Generator
@author François Cardinaux, CH 1207 Genève
@copyright 2012 François Cardinaux

Licence: see README.md

Things to be aware of when using clojure compiler's advanced optimization
=========================================================================

Read https://developers.google.com/closure/compiler/docs/api-tutorial3#dangers

In particular:
* When accessing an object's element, always use the same method: either myObject['myKey'] or myObject.myKey
* Observe the way the NoCompile is created and used to export the symbols that must be kept after clojure compiler's advanced optimization

###

class CMGBitBoard

    # Not used. Remove comments if needed
    # @EMPTY_BOARD    = [0, 0, 0, 0]
    # @FULL_BOARD     = [0xffff, 0xffff, 0xffff, 0xffff]

    # Note:
    # @SQUARE_VALUES and @SQUARE_QUADRANTS_AND_VALUES are generated by a metaprogram and placed at the END of this javascript

    # -------------------------------------------------------------------------
    # Bitboard maths (functions of class and of instance)

    @clone: (bb) ->
        [bb[0], bb[1], bb[2], bb[3]]

    @binEqual: (bb1, bb2) ->
        for quadrantId in [0..3]
            if bb1[quadrantId] isnt bb2[quadrantId]
                return false
        return true

    # Not used. Remove comments if needed
    # @isZero: (bb) ->
    #     @binEqual(bb, @EMPTY_BOARD)

    @boolNand: (bb1, bb2) ->
        # On average quicker than "@isZero( @binAnd(bb1, bb2) )"
        (0 is (bb1[0] & bb2[0])) and (0 is (bb1[1] & bb2[1])) and (0 is (bb1[2] & bb2[2])) and (0 is (bb1[3] & bb2[3]))

    @binAnd: (bb1, bb2) ->
        [
            bb1[0] & bb2[0],
            bb1[1] & bb2[1],
            bb1[2] & bb2[2],
            bb1[3] & bb2[3]
        ]

    # Not used. Remove comments if needed
    # @boolOr: (bb1, bb2) ->
    #     # On average quicker than "not @isZero( @binOr(bb1, bb2) )"
    #     (0 < (bb1[0] & bb2[0])) or (0 < (bb1[1] & bb2[1])) or (0 < (bb1[2] & bb2[2])) or (0 < (bb1[3] & bb2[3]))

    @binOr: (bb1, bb2) ->
        [
            bb1[0] | bb2[0],
            bb1[1] | bb2[1],
            bb1[2] | bb2[2],
            bb1[3] | bb2[3]
        ]

    # Not used. Remove comments if needed
    # @binXor: (bb1, bb2) ->
    #     [
    #         bb1[0] ^ bb2[0],
    #         bb1[1] ^ bb2[1],
    #         bb1[2] ^ bb2[2],
    #         bb1[3] ^ bb2[3]
    #     ]

    @binNot: (bb) ->
        [
            ~ bb[0] & 0xffff,
            ~ bb[1] & 0xffff,
            ~ bb[2] & 0xffff,
            ~ bb[3] & 0xffff
        ]

    @valueOfSquare: (square) ->
        @SQUARE_VALUES[square]

    @quadrantAndValueOfSquare: (square) ->
        @SQUARE_QUADRANTS_AND_VALUES[square]

    @bitBoardToSquareKeyArray: ( bitBoard ) ->
        squareKeys = []
        for quadrant, qid in bitBoard
            for key in [0..15]
                if (1 << key) & quadrant
                    squareKeys.push(qid * 16 + key)
        return squareKeys

# =============================================================================

class CMGPosition
    # -------------------------------------------------------------------------
    # Only for tests:
    @PSEUDO_ONLY = false

    # -------------------------------------------------------------------------
    # Noticeable values:
    @ROW_SPAN:              8
    @BOTTOM_LEFT_CORNER:    0
    @BOTTOM_RIGHT_CORNER:   7
    @TOP_LEFT_CORNER:       56
    @TOP_RIGHT_CORNER:      63

    # -------------------------------------------------------------------------
    # Internal encoding for castling:
    @CASTLING_CODE_ALL:         15
    @CASTLING_CODE_WHITE_KING:   8
    @CASTLING_CODE_WHITE_QUEEN:  4
    @CASTLING_CODE_BLACK_KING:   2
    @CASTLING_CODE_BLACK_QUEEN:  1
    @CASTLING_CODE_ANY_KING:    @CASTLING_CODE_WHITE_KING  | @CASTLING_CODE_BLACK_KING
    @CASTLING_CODE_ANY_QUEEN:   @CASTLING_CODE_WHITE_QUEEN | @CASTLING_CODE_BLACK_QUEEN

    # -------------------------------------------------------------------------
    # Move bitboards
    # Note:
    # @QUEEN_MOVES, @ROOK_MOVES, @BISHOP_MOVES, @KNIGHT_MOVES,
    # @KING_MOVES_WITHOUT_CASTLING, @PAWN_NON_TAKING_MOVES, @PAWN_TAKING_MOVES
    # and @SHADOWS are generated by a metaprogram and placed at the END of this javascript

    @CASTLING_WHITE_KING:   { move: [ 64, 0, 0,     0 ], mustBeEmptyOnQuadrant0: 96 } # Move = king position (  16) x 4
    @CASTLING_WHITE_QUEEN:  { move: [  4, 0, 0,     0 ], mustBeEmptyOnQuadrant0: 14 } # Move = king position (  16) / 4
    @CASTLING_BLACK_KING:   { move: [  0, 0, 0, 16384 ], mustBeEmptyOnQuadrant3: 24576 } # Move = king position (4096) x 4
    @CASTLING_BLACK_QUEEN:  { move: [  0, 0, 0,  1024 ], mustBeEmptyOnQuadrant3: 3584 } # Move = king position (4096) / 4

    # -------------------------------------------------------------------------
    # Public functions of class (comparable to static methods)

    @fromString: (positionString) ->
        ###
        Get an object instance from its Forsyth-Edwards representation
        ###
        elements = positionString.split(' ')
        [boardString, turnChar, allowedCastlingString, enPassantString] = elements

        halfMoveClock = 0
        moveNumber = 1
        switch elements.length
            when 5
                halfMoveClock = parseInt(elements[4])
            when 6
                halfMoveClock = parseInt(elements[4])
                moveNumber = parseInt(elements[5])

        # Process each element one by one
        pieces            = CMGPosition._boardStringToPieces(boardString)
        allowedCastling   = CMGPosition._allowedCastlingStringToValue(allowedCastlingString)
        enPassantSquare   = CMGPosition._enPassantStringToSquare(enPassantString)
        turn              = CMGPosition._turnCharToValue(turnChar)

        # Return the position
        new CMGPosition(pieces, turn, allowedCastling, enPassantSquare, halfMoveClock, moveNumber)

    @squareNumberToString: (squareNumber) ->
        rowValue = Math.floor(squareNumber / CMGPosition.ROW_SPAN)
        colValue = squareNumber % CMGPosition.ROW_SPAN

        String.fromCharCode(colValue + 97) + String.fromCharCode(rowValue + 49) # 97 is 'a', 49 is '1'

    # -------------------------------------------------------------------------
    # Private functions of class (comparable to static methods)

    @_boardStringToPieces: (boardString) ->
        # Reverse, so that the table SquareTabId is immediately ordered by square ID
        rowStrings = boardString.split('/').reverse()
        CMGPosition._rowStringsToPieces(rowStrings)

    @_rowStringsToPieces: (rowStrings, pieces = [], rowId = 0) ->
        if rowStrings.length isnt 8
            throw "Incorrect number of rows in #{rowStrings}"

        pieces = {}

        for rowString, rowId in rowStrings
            pieces = CMGPosition._squareCharsToPieces(rowString.split(''), pieces, rowId * CMGPosition.ROW_SPAN, rowId * CMGPosition.ROW_SPAN + 7)

        return pieces

    @_squareCharsToPieces: (rowChars, pieces, currentSquareId, lastSquareIdOfRow) ->
        for rowChar in rowChars
            switch rowChar
                when '1' then currentSquareId += 1 # when character is '1'
                when '2' then currentSquareId += 2
                when '3' then currentSquareId += 3
                when '4' then currentSquareId += 4
                when '5' then currentSquareId += 5
                when '6' then currentSquareId += 6
                when '7' then currentSquareId += 7
                when '8' then currentSquareId += 8 # when character is '8'
                else
                    pieces[currentSquareId] = CMGPiece.fromChar( rowChar )
                    currentSquareId += 1

        return pieces

    @_allowedCastlingStringToValue: (allowedCastlingString) ->
        if allowedCastlingString is '-'
            return 0

        func = (acc, pce) ->
            switch pce
                when 'K' then return acc + CMGPosition.CASTLING_CODE_WHITE_KING
                when 'Q' then return acc + CMGPosition.CASTLING_CODE_WHITE_QUEEN
                when 'k' then return acc + CMGPosition.CASTLING_CODE_BLACK_KING
                when 'q' then return acc + CMGPosition.CASTLING_CODE_BLACK_QUEEN
            acc

        allowedCastlingString.split('').reduce(func, 0)

    @_allowedCastlingValueToString: (allowedCastling) ->
        if allowedCastling is 0
            return '-'

        wqChar = wkChar = bqChar = bkChar = ''
        wqChar = 'Q' if allowedCastling & CMGPosition.CASTLING_CODE_WHITE_QUEEN
        wkChar = 'K' if allowedCastling & CMGPosition.CASTLING_CODE_WHITE_KING
        bqChar = 'q' if allowedCastling & CMGPosition.CASTLING_CODE_BLACK_QUEEN
        bkChar = 'k' if allowedCastling & CMGPosition.CASTLING_CODE_BLACK_KING

        allowedCastlingString = [wkChar, wqChar, bkChar, bqChar].join('')

        return allowedCastlingString

    @_enPassantStringToSquare: (enPassantString) ->
        if enPassantString is '-'
            return false

        if enPassantString.length isnt 2
            throw "Invalid en-passant string: #{enPassantString}"
        colValue = enPassantString.charCodeAt(0) - 97 # 'a' in ascii
        rowValue = enPassantString.charCodeAt(1) - 49 # '1' in ascii
        CMGPosition._squareReference(rowValue, colValue)

    @_turnCharToValue: (turnChar) ->
        if turnChar isnt 'b' and turnChar isnt 'w'
            throw "Invalid turn character: #{turnChar}"

        return turnChar

    @_squareReference: (rowId, colId) ->
        CMGPosition.ROW_SPAN * rowId + colId

    @_getPieceOnSquare: (item, squareKey) ->
        pieces = null
        if item instanceof CMGPosition
            pieces = item.pieces
        else
            pieces = item

        if not pieces.hasOwnProperty(squareKey)
            return false

        return pieces[squareKey]

    @_shadow: (square, direction) ->
        # @param direction (int): 0 = north, 1 = north-east, ..., 7 = north-west (i.e. clockwise)
        @SHADOWS[square][direction]

    @_light: (square, direction) ->
        # @param direction (int): 0 = north, 1 = north-east, ..., 7 = north-west (i.e. clockwise)
        @SHADOWS[square][direction ^ 4] # ^ = xor

    @_oppositeColor: (color, defaultValue = false) ->
        switch color
            when "b" then return "w"
            when "w" then return "b"
        defaultValue

    @_direction: (arrowFrom, arrowTo, arrowFromIs0x88 = false) ->
        # Using 0x88 representation allows to check diagonals easily.
        # Without it, doing a simple modulo operation (%9 and %7) would lead to boundary errors.
        b_0x88 = CMGUtil.to0x88representation( arrowTo )
        a_0x88 = CMGUtil.to0x88representation( arrowFrom )  if not arrowFromIs0x88
        a_0x88 = arrowFrom                                  if arrowFromIs0x88
        delta = b_0x88 - a_0x88
        return [false, 0] if delta is 0
        absDelta = Math.abs(delta)
        clg.log([b_0x88, a_0x88, delta])

        if absDelta < 8 # Same row
            return [2, absDelta] if delta > 0
            return [6, absDelta]
        else if absDelta % 16 is 0 # Same column
            return [0, absDelta] if delta > 0
            return [4, absDelta]
        else if absDelta % 17 is 0 # Same diagonal NE - SW
            return [1, absDelta] if delta > 0
            return [5, absDelta]
        else if absDelta % 15 is 0 # Same diagonal NW - SE
            return [7, absDelta] if delta > 0
            return [3, absDelta]

        return [false, absDelta]

    # -------------------------------------------------------------------------
    # Constructor

    constructor: (@pieces, @turn, @allowedCastling = 0, @enPassantSquare = false, @halfMoveClock = 0, @moveNumber = 0) ->
        ###
        Constructor
        @param pieces (Object) With object keys = square ids and object values = instances of CMGPiece
        @param turn (false|"b"|"w")
        @param allowedCastling (integer)
        @param enPassantSquare (false|integer where integer is between 0 (bottom right corner) and 63 (top right corner)
        @param halfMoveClock (integer)
        @param moveNumber (integer)
        ###

        @kingSquare = false

        @piecesOfColor = {}
        @piecesOfColor['b'] = {}
        @piecesOfColor['w'] = {}

        if @pieces
            # This test is necessary, because if CMGUtil.cloneObject() is used, the object is first created empty

            for squareId, piece of @pieces
                @piecesOfColor[piece.color][squareId] = piece
                if piece.color is @turn and piece.type is 'k'
                    @kingSquare = squareId

        @bitBoards = {}
        @_generateBitBoards()

        # May be used, e.g., for castling evaluation:
        @lazy = {}

    # -------------------------------------------------------------------------
    # Public functions of object (comparable to non static methods)

    clone: (pieces = false, withLazyObject = false) ->
        if not pieces
            pieces = @pieces
        out = new CMGPosition(pieces, @turn, @allowedCastling, @enPassantSquare, @halfMoveClock, @moveNumber)
        if withLazyObject
            out.lazy = CMGUtil.cloneObject( @lazy )
        return out

    playerColorCode: () ->
        @turn

    opponentColorCode: () ->
        CMGPosition._oppositeColor(@turn)

    toString: () ->
        ###
        Get the Forsyth-Edwards representation of the object
        ###
        [@toStringWithoutCounters(), @halfMoveClock, @moveNumber].join(' ')

    toStringWithoutCounters: () ->
        boardString = @_piecesToBoardString(@pieces)
        turnChar = @turn # neither filtering nor transformation necessary in this direction
        allowedCastlingString = CMGPosition._allowedCastlingValueToString(@allowedCastling)
        enPassantString = @_enPassantSquareToString(@enPassantSquare)

        [boardString, turnChar, allowedCastlingString, enPassantString].join(' ')

    isValidMove: (fromSquare, toSquare, promotion = false) ->
        move = CMGMove.fromPositionAndMoveCoordinates(this, fromSquare, toSquare, promotion)
        return ( move instanceof CMGMove )

    allPossibleMovesFrom: (squareKey, piece = null) ->
        ###
        All possible moves from the specifed square key.
        If possible, pass the piece on that square as second parameter. If absent, it will be retreived from the @pieces object.
        @return (array)
        ###
        squareKey = CMGUtil.toString(squareKey)

        if not piece
            piece = @_getPieceOnSquare(squareKey)

        if not piece
            return []

        if piece.color isnt @turn
            return []

        # Search all pseudo moves from the given square
        pseudoMoves = @_allPseudoMovesFromSquare(squareKey)

        # Finally, eliminate invalid moves:
        out = []

        for pseudoMove in pseudoMoves
            if pseudoMove.isValidPseudoMove()
                out.push(pseudoMove)

        return out

    allPossibleMoves: () ->
        result = []

        for square, piece of @pieces
            if piece.color isnt @turn
                continue
            moves = @allPossibleMovesFrom(square, piece)
            if moves.length > 0
                result = result.concat(moves)

        return result

    isDraw: () ->
        ###
        Is the position a draw
        @return boolean
        ###
        return 'todo'

    getWinnerColorCode: () ->
        ###
        Get the winner color code
        @return (false|'b'|'w')
        ###
        return 'todo'

    # -------------------------------------------------------------------------
    # Private functions of object (comparable to non static methods)

    _opponentKingAttacked: () ->
        opponentKingBitBoard = @bitBoards.allPiecesOfColorAndType[@opponentColorCode()]['k']
        return not CMGBitBoard.boolNand( opponentKingBitBoard, @_allPseudoMoveBitBoard() )

    _directionOfKingProtectionByOriginatingSquareOfNonKingMove: (move) ->
        if not @lazy.hasOwnProperty('kprot1')
            @lazy['kprot1'] = {}

        squareKey = CMGUtil.toString( move.fromSquare )
        if not @lazy['kprot1'].hasOwnProperty(squareKey)

            # Test if direction is relevant
            [supposedProtectionDirection, dummy] = CMGPosition._direction(move.fromSquare, @kingSquare)

            clg.log("supposedProtectionDirection = #{supposedProtectionDirection} if protecting is on #{move.fromSquare} and king is on #{@kingSquare}")

            if supposedProtectionDirection is false
                @lazy['kprot1'][squareKey] = false
                return @lazy['kprot1'][squareKey]

            # Calculate some useful values from supposedProtectionDirection
            switch supposedProtectionDirection
                when 0 then [towardsKing, oppositeDirection, nonQueenCandidate] = [ 8, 4, 'r'] # the other candidate is the queen
                when 4 then [towardsKing, oppositeDirection, nonQueenCandidate] = [-8, 0, 'r'] #  "    "       "     "   "    "
                when 1 then [towardsKing, oppositeDirection, nonQueenCandidate] = [ 9, 5, 'b'] #  "    "       "     "   "    "
                when 5 then [towardsKing, oppositeDirection, nonQueenCandidate] = [-9, 1, 'b'] #  "    "       "     "   "    "
                when 2 then [towardsKing, oppositeDirection, nonQueenCandidate] = [ 1, 6, 'r'] #  "    "       "     "   "    "
                when 6 then [towardsKing, oppositeDirection, nonQueenCandidate] = [-1, 2, 'r'] #  "    "       "     "   "    "
                when 3 then [towardsKing, oppositeDirection, nonQueenCandidate] = [-7, 7, 'b'] #  "    "       "     "   "    "
                when 7 then [towardsKing, oppositeDirection, nonQueenCandidate] = [ 7, 3, 'b'] #  "    "       "     "   "    "

            clg.log([towardsKing, oppositeDirection, nonQueenCandidate])

            # Now test if there anything between the evaluated square and the king
            pieceFoundTowardsKing = false
            evalSquare = CMGUtil.toInteger( move.fromSquare )
            while pieceFoundTowardsKing is false
                evalSquare += towardsKing
                clg.log(evalSquare)
                pieceFoundTowardsKing = @_getPieceOnSquare(evalSquare)
                if evalSquare < 0 or evalSquare > 63
                    throw "Oops! Invalid square #{evalSquare}. Moving out of the board towards direction #{supposedProtectionDirection} without encoutering any king?"

            clg.log("pieceFoundTowardsKing = #{pieceFoundTowardsKing.type} #{pieceFoundTowardsKing.color}")

            if pieceFoundTowardsKing.type isnt 'k' or pieceFoundTowardsKing.color isnt @turn
                # King is protected by more than one piece in this direction
                @lazy['kprot1'][squareKey] = false
                return @lazy['kprot1'][squareKey]

            # Now test if king would be attacked FROM THIS DIRECTION if the evaluated square were empty
            # todo reprendre. Il faut tester les boundaries si la piece deplacee est manquante. De plus, il vaut mieux ne tester que la direction de la piece.
            kingBoundaries = @_kingBoundaries(oppositeDirection, move.fromSquare)
            clg.log('King boundaries: ')
            clg.log(kingBoundaries, true)

            opponent = @opponentColorCode()
            clg.log('opponent is ' + opponent)

            candidateBitBoard = CMGBitBoard.binOr( @bitBoards.allPiecesOfColorAndType[opponent]['q'], @bitBoards.allPiecesOfColorAndType[opponent][nonQueenCandidate] )
            clg.log(candidateBitBoard, true)
            if CMGBitBoard.boolNand( candidateBitBoard, kingBoundaries )
                # No threat if evaluated square is emptied, so no protection from evaluated piece
                @lazy['kprot1'][squareKey] = false
                return @lazy['kprot1'][squareKey]

            @lazy['kprot1'][squareKey] = supposedProtectionDirection

        @lazy['kprot1'][squareKey]

    _attackedKingProtectedByTargetSquareOfNonKingMove: (move) ->
        if not @lazy.hasOwnProperty('kprot2')
            @lazy['kprot2'] = {}

        squareKey = CMGUtil.toString( move.toSquare )
        clg.log("Move to #{squareKey}")
        if not @lazy['kprot2'].hasOwnProperty(squareKey)

            # Here, we assume the king is attacked before the move, or that it was protected by the moved piece before it moved.
            # We also assume the move is not a pawn taking another "en passant".
            # All these conditions are assumed to be valid when this function is called.

            clg.log(move.getNewPosition().toString())
            # Test if king under attack after sample protecting move
            @lazy['kprot2'][squareKey] = not move.getNewPosition()._opponentKingAttacked() # opponent of new position, i.e. player of current position

        @lazy['kprot2'][squareKey]

    _getNewPositionObjectAfterMove: (move) ->
        pieces = CMGUtil.cloneObject( @pieces )

        pieces[move.fromSquare] = null # ensure garbage collection
        delete pieces[move.fromSquare] # remove the element from the object

        if move.takenOnSquare
            pieces[move.takenOnSquare] = null # ensure garbage collection
            delete pieces[move.takenOnSquare] # remove the element from the object

        pieces[move.toSquare] = move.toPiece

        # Move the rook if castling
        if move.castling is 'k'
            if @turn is 'b'
                pieces[61] = pieces[63]
                delete pieces[63]
            if @turn is 'w'
                pieces[5] = pieces[7]
                delete pieces[7]
        else if move.castling is 'q'
            if @turn is 'b'
                pieces[59] = pieces[56]
                delete pieces[56]
            if @turn is 'w'
                pieces[3] = pieces[0]
                delete pieces[0]

        turn = @opponentColorCode()

        # Determine new 'allowed castling' value
        allowedCastling = @allowedCastling
        switch parseInt(move.fromSquare)
            when   0 then allowedCastling &= ( ~ CMGPosition.CASTLING_CODE_WHITE_QUEEN )
            when   4 then allowedCastling &= ( ~ CMGPosition.CASTLING_CODE_WHITE_QUEEN & ~ CMGPosition.CASTLING_CODE_WHITE_KING )
            when   7 then allowedCastling &= ( ~ CMGPosition.CASTLING_CODE_WHITE_KING )
            when  56 then allowedCastling &= ( ~ CMGPosition.CASTLING_CODE_BLACK_QUEEN )
            when  60 then allowedCastling &= ( ~ CMGPosition.CASTLING_CODE_BLACK_QUEEN & ~ CMGPosition.CASTLING_CODE_BLACK_KING )
            when  63 then allowedCastling &= ( ~ CMGPosition.CASTLING_CODE_BLACK_KING )

        if move.takenOnSquare isnt false and move.takenPiece.type is 'r'
            switch parseInt(move.takenOnSquare)
                when   0 then allowedCastling &= ( ~ CMGPosition.CASTLING_CODE_WHITE_QUEEN )
                when   4 then allowedCastling &= ( ~ CMGPosition.CASTLING_CODE_WHITE_QUEEN & ~ CMGPosition.CASTLING_CODE_WHITE_KING )
                when   7 then allowedCastling &= ( ~ CMGPosition.CASTLING_CODE_WHITE_KING )
                when  56 then allowedCastling &= ( ~ CMGPosition.CASTLING_CODE_BLACK_QUEEN )
                when  60 then allowedCastling &= ( ~ CMGPosition.CASTLING_CODE_BLACK_QUEEN & ~ CMGPosition.CASTLING_CODE_BLACK_KING )
                when  63 then allowedCastling &= ( ~ CMGPosition.CASTLING_CODE_BLACK_KING )

        enPassantSquare = false
        if move.fromPiece.type is 'p'
            pawnJump = move.toSquare - move.fromSquare
            if Math.abs( pawnJump ) is 16
                enPassantSquare = move.toSquare - pawnJump / 2

        halfMoveClock   = @halfMoveClock
        moveNumber      = @moveNumber
        if moveNumber is 0
            # Without counters
            halfMoveClock = 0
        else
            # With counters
            if turn is 'w'
                moveNumber += 1

            if move.fromPiece.type is 'p'
                halfMoveClock = 0
            else if move.takenPiece
                halfMoveClock = 0
            else
                halfMoveClock += 1

        out = new CMGPosition(pieces, turn, allowedCastling, enPassantSquare, halfMoveClock, moveNumber)
        out

    _allPseudoMoves: () ->
        # These lazy objects are useful in case of chained move generation, typically during the "performance test" (perftsuite.txt)
        if not @lazy.hasOwnProperty('pmv')
            @lazy['pmv'] = [] # Pseudo-move array
            @lazy['pmvs'] = {} # Pseudo-move arrays, one element for each of player's piece
            @lazy['pmvbb'] = [0, 0, 0, 0] # Pseudo-move bitboard
            @lazy['pqrbmvbb'] = [0, 0, 0, 0] # Pseudo-move of queens, rooks and bishops bitboard

            # Temporary bitboard, to reduce the number of binOr operations by calculating @lazy['pmvbb'] only at the end of loop
            temp_pqrbmvbb     = [0, 0, 0, 0]
            temp_not_pqrbmvbb = [0, 0, 0, 0]

            opponent = @opponentColorCode()
            for squareKey, piece of @piecesOfColor[@turn]
                @lazy['pmvs'][squareKey] = []

                # First, seach all "ordinary" pseudo moves
                pseudoMoveBitBoard = @_bitBoardOfPseudoMovesFromSquare(squareKey, piece, @turn, opponent)

                if piece.type is 'b' or piece.type is 'r' or piece.type is 'q'
                    temp_pqrbmvbb = CMGBitBoard.binOr( temp_pqrbmvbb, pseudoMoveBitBoard )
                else
                    temp_not_pqrbmvbb = CMGBitBoard.binOr( temp_not_pqrbmvbb, pseudoMoveBitBoard )

                # Second, convert the move bitboard into a move array, and execute promotion if required
                targets = CMGBitBoard.bitBoardToSquareKeyArray( pseudoMoveBitBoard )
                for target in targets
                    toPiece = piece

                    takenPiece = @_getPieceOnSquare(target)
                    takenOnSquare = false
                    if takenPiece
                        takenOnSquare = target
                    else if piece.type is 'p' and parseInt(target) is @enPassantSquare
                        # Still need to verify if taken 'en passant':
                        iSquareKey = parseInt(squareKey)
                        switch @enPassantSquare - iSquareKey
                            when -9 then takenOnSquare = iSquareKey - 1
                            when -7 then takenOnSquare = iSquareKey + 1
                            when  7 then takenOnSquare = iSquareKey - 1
                            when  9 then takenOnSquare = iSquareKey + 1
                        if takenOnSquare
                            takenPiece = @_getPieceOnSquare(takenOnSquare)

                    if piece.type is 'p' and (target >= CMGPosition.TOP_LEFT_CORNER or target <= CMGPosition.BOTTOM_RIGHT_CORNER)
                        # A promotion
                        for newPieceType in ['q', 'r', 'n', 'b']
                            newPiece = new CMGPiece(piece.color, newPieceType)
                            move = new CMGMove(this, squareKey, piece, target, newPiece, false, takenPiece, takenOnSquare)
                            @lazy['pmvs'][squareKey].push(move)
                    else
                        castling = false
                        if piece.type is 'k' and Math.abs(target - squareKey) is 2
                            if target > squareKey
                                castling = 'k'
                            else
                                castling = 'q'
                        move = new CMGMove(this, squareKey, piece, target, toPiece, castling, takenPiece, takenOnSquare)
                        @lazy['pmvs'][squareKey].push(move)

            @lazy['pmvbb'] = CMGBitBoard.binOr( temp_pqrbmvbb, temp_not_pqrbmvbb )
            @lazy['pqrbmvbb'] = CMGBitBoard.clone( temp_pqrbmvbb )

        return @lazy['pmv']

    _allPseudoMovesFromSquare: (squareKey) ->
        # todo rationalize: avoid loading all pseudo moves from all squares here
        if not @lazy.hasOwnProperty('pmvs')
            @_allPseudoMoves()
        if not @lazy['pmvs'].hasOwnProperty(squareKey)
            return []
        return @lazy['pmvs'][squareKey]

    _allPseudoMoveBitBoard: () ->
        if not @lazy.hasOwnProperty('pmvbb')
            @_allPseudoMoves()
        return @lazy['pmvbb']

    _allPseudoQRBMoveBitBoard: () ->
        if not @lazy.hasOwnProperty('pqrbmvbb')
            @_allPseudoMoves()
        return @lazy['pqrbmvbb']

    _castlingPossibleOnSide: (castlingSide) ->
        if not @lazy.hasOwnProperty('pks')

            @lazy['pks'] =
                'k': 0 < (@allowedCastling & CMGPosition.CASTLING_CODE_ANY_KING)
                'q': 0 < (@allowedCastling & CMGPosition.CASTLING_CODE_ANY_QUEEN)

            if @lazy['pks']['k'] or @lazy['pks']['q']

                threats = @_pseudoThreatsOnPlayerBeforeMove()

                kingSquareBitBoard = @bitBoards.allPiecesOfColorAndType[@turn]['k']
                kingQuadrant = 0
                if @turn is 'b'
                    kingQuadrant = 3

                if 0 < ( kingSquareBitBoard[kingQuadrant] & threats[kingQuadrant] )
                    @lazy['pks']['k'] = false
                    @lazy['pks']['q'] = false
                else
                    if @lazy['pks']['k']
                        @lazy['pks']['k'] = false if 0 < ( (kingSquareBitBoard[kingQuadrant] << 1) & threats[kingQuadrant] )

                    if @lazy['pks']['q']
                        @lazy['pks']['q'] = false if 0 < ( (kingSquareBitBoard[kingQuadrant] >> 1) & threats[kingQuadrant] )

        return @lazy['pks'][castlingSide]

    _pseudoThreatsOnPlayerBeforeMove: () ->
        if not @lazy.hasOwnProperty('ptpbm')

            invPosition = @clone() # Lazy object not cloned, thus the pseudo-move bitboard will be recalculated
            invPosition.turn = @opponentColorCode()
            invPosition.enPassantSquare = false
            invPosition.allowedCastling = false # Avoid unnecessary evaluations

            @lazy['ptpbm'] = invPosition._allPseudoMoveBitBoard()

            @lazy['ptfqrbpbm'] = invPosition._allPseudoQRBMoveBitBoard()

        return @lazy['ptpbm']

    _pseudoThreatsFromQRBOnPlayerBeforeMove: () ->
        if not @lazy.hasOwnProperty('ptfqrbpbm')
            @_pseudoThreatsOnPlayerBeforeMove()
        return @lazy['ptfqrbpbm']

    _kingBoundaries: (direction, emptiedSquareKey) ->
        ###
        Bitmap of boundaries seen by the player's king, when the specified square is emptied.
        Only the specified direction is evaluated.
        ###
        if not @lazy.hasOwnProperty('king-boundaries')
            @lazy['king-boundaries'] = {}

        if not @lazy['king-boundaries'].hasOwnProperty(emptiedSquareKey)
            @lazy['king-boundaries'][emptiedSquareKey] = @_computeBoundaries(@kingSquare, direction, emptiedSquareKey)

        return @lazy['king-boundaries'][emptiedSquareKey]


    _bitBoardOfPseudoMovesFromSquare: (squareKey, movedPiece, stopAtColor = false, stopAfterColor = false) ->
        out = [0, 0, 0, 0]

        if not movedPiece
            return [0, 0, 0, 0]

        switch movedPiece.type
            when 'r'
                shadows = @_computeShadows(squareKey, [0, 2, 4, 6], stopAtColor, stopAfterColor)
                out = CMGBitBoard.binAnd( CMGPosition.ROOK_MOVES[squareKey], CMGBitBoard.binNot(shadows) )
            when 'n'
                out = CMGBitBoard.binAnd( CMGPosition.KNIGHT_MOVES[squareKey], CMGBitBoard.binNot( @bitBoards.allPiecesOfColor[@turn]) )
            when 'b'
                shadows = @_computeShadows(squareKey, [1, 3, 5, 7], stopAtColor, stopAfterColor)
                out = CMGBitBoard.binAnd( CMGPosition.BISHOP_MOVES[squareKey], CMGBitBoard.binNot(shadows) )
            when 'q'
                shadows = @_computeShadows(squareKey, [0..7], stopAtColor, stopAfterColor)
                out = CMGBitBoard.binAnd( CMGPosition.QUEEN_MOVES[squareKey], CMGBitBoard.binNot(shadows) )
            when 'k'
                shadows = @_computeShadows(squareKey, [0..7], stopAtColor, stopAfterColor)
                out = CMGBitBoard.binAnd( CMGPosition.KING_MOVES_WITHOUT_CASTLING[squareKey], CMGBitBoard.binNot(shadows) )

                # Castling move if any
                if movedPiece.color is 'b'
                    if (@allowedCastling & CMGPosition.CASTLING_CODE_BLACK_KING)  and 0 is ( @bitBoards.allPieces[3] & CMGPosition.CASTLING_BLACK_KING.mustBeEmptyOnQuadrant3 )
                        out = CMGBitBoard.binOr( out, CMGPosition.CASTLING_BLACK_KING.move )
                    if (@allowedCastling & CMGPosition.CASTLING_CODE_BLACK_QUEEN) and 0 is ( @bitBoards.allPieces[3] & CMGPosition.CASTLING_BLACK_QUEEN.mustBeEmptyOnQuadrant3 )
                        out = CMGBitBoard.binOr( out, CMGPosition.CASTLING_BLACK_QUEEN.move )
                else
                    if (@allowedCastling & CMGPosition.CASTLING_CODE_WHITE_KING)  and 0 is ( @bitBoards.allPieces[0] & CMGPosition.CASTLING_WHITE_KING.mustBeEmptyOnQuadrant0 )
                        out = CMGBitBoard.binOr( out, CMGPosition.CASTLING_WHITE_KING.move )
                    if (@allowedCastling & CMGPosition.CASTLING_CODE_WHITE_QUEEN) and 0 is ( @bitBoards.allPieces[0] & CMGPosition.CASTLING_WHITE_QUEEN.mustBeEmptyOnQuadrant0 )
                        out = CMGBitBoard.binOr( out, CMGPosition.CASTLING_WHITE_QUEEN.move )

            when 'p'
                shadowDirections = [0] if @turn is 'w'
                shadowDirections = [4] if @turn is 'b'
                allShadows = @_computeShadows(squareKey, shadowDirections, '*')

                # Remember that CMGPosition.PAWN_(NON_)TAKING_MOVES[<color>] is shorter, because pawns on raws 1 and 8 cannot take anything
                pawnMoveArrayKey = squareKey - 8
                nonTakingMoves = CMGBitBoard.binAnd( CMGPosition.PAWN_NON_TAKING_MOVES[@turn][pawnMoveArrayKey], CMGBitBoard.binNot(allShadows) )
                takingMoves = CMGBitBoard.binAnd( CMGPosition.PAWN_TAKING_MOVES[@turn][pawnMoveArrayKey], CMGBitBoard.binNot( @bitBoards.allPiecesOfColor[@turn] ) )
                out = CMGBitBoard.binOr( takingMoves, nonTakingMoves )

        return out

    _computeBoundaries: (origin, directionFilter, skipPieceSquare) ->
        ###
        Compute the boundaries seen from origin in the specified direction
        ###
        origin = CMGUtil.toInteger( origin )
        origin0x88value = CMGUtil.to0x88representation( origin )
        skipPieceSquare = CMGUtil.toInteger( skipPieceSquare )

        boundaryList = [false, false, false, false, false, false, false, false] # One for each direction
        for pieceSquare, piece of @pieces
            pieceSquare = CMGUtil.toInteger( pieceSquare )
            if pieceSquare is origin
                continue # skip the light origin itself
            if pieceSquare is skipPieceSquare
                continue
            [direction, distance] = CMGPosition._direction(origin0x88value, pieceSquare, true) # Third parameter is optimization
            if direction is false or direction isnt directionFilter
                continue
            if boundaryList[direction] is false or boundaryList[direction][0] > distance
                boundaryList[direction] = [distance, pieceSquare]

        boundaries = [0, 0, 0, 0]
        for boundaryDef in boundaryList
            if boundaryDef is false
                continue
            [dummy, boundarySquare] = boundaryDef
            [boundaryQuadrant, boundaryValue] = CMGBitBoard.quadrantAndValueOfSquare(boundarySquare)
            boundaries[boundaryQuadrant] |= boundaryValue

        return boundaries


    _computeShadows: (squareKey, directions, stopAtColor = '*', stopAfterColor = false) ->

        shadowMap = [0, 0, 0, 0]

        if stopAtColor
            shadowMap = CMGBitBoard.binOr( shadowMap, @_computeSingleBehaviorShadows(squareKey, directions, stopAtColor, false) )

        if stopAfterColor
            shadowMap = CMGBitBoard.binOr( shadowMap, @_computeSingleBehaviorShadows(squareKey, directions, stopAfterColor, true) )

        return shadowMap

    _computeSingleBehaviorShadows: (squareKey, directions, stoppingColor = '*', stopAfterOnly = false) ->
        shadowMap = [0, 0, 0, 0]

        pieces = null
        if stoppingColor is '*'
            pieces = @pieces
        else
            pieces = @piecesOfColor[stoppingColor]

        squareKeyBitBoard = CMGBitBoard.valueOfSquare(squareKey)

        for pieceSquare, piece of pieces
            if pieceSquare is squareKey
                continue # skip the light origin itself

            exclusionQuadrant = false
            exclusionValue = false
            if stopAfterOnly
                [exclusionQuadrant, exclusionValue] = CMGBitBoard.quadrantAndValueOfSquare( parseInt(pieceSquare) )
                exclusionValue = (~ exclusionValue) & 0xffff

            for direction in directions
                if not CMGBitBoard.boolNand( CMGPosition._light(pieceSquare, direction), squareKeyBitBoard )
                    newShadows = CMGBitBoard.clone( CMGPosition._shadow(pieceSquare, direction) )
                    if stopAfterOnly
                        newShadows[exclusionQuadrant] &= exclusionValue
                    shadowMap = CMGBitBoard.binOr( shadowMap, newShadows )
                    break # correct direction found, break 1 level
        return shadowMap

    _piecesToBoardString: () ->
        ( @_piecesToRowStrings() ).join('/')

    _piecesToRowStrings: () ->
        rowId = 8
        rowStrings = []

        while rowId > 0
            rowId--
            rowStrings.push( @_piecesOnRowToRowString(rowId) )

        return rowStrings

    _piecesOnRowToRowString: (rowId) ->
        colId = 0
        rowChars = []
        emptySquareCounter = 0

        while colId < 8

            squareKey = CMGPosition._squareReference(rowId, colId)
            pieceFound = @_getPieceOnSquare(squareKey)

            if pieceFound is false
                emptySquareCounter++
            else
                pieceChar = pieceFound.toChar()
                if emptySquareCounter > 0
                    rowChars.push(emptySquareCounter)
                rowChars.push(pieceChar)
                emptySquareCounter = 0

            colId++

        if emptySquareCounter isnt 0
            rowChars.push(emptySquareCounter)

        rowChars.join('')

    _enPassantSquareToString: (squareNumber) ->
        if squareNumber is false
            return '-'

        return CMGPosition.squareNumberToString(squareNumber)

    _getPieceOnSquare: (squareKey) ->
        CMGPosition._getPieceOnSquare(@pieces, squareKey)

    _generateBitBoards: () ->
        @bitBoards.allPieces = [0, 0, 0, 0]
        @bitBoards.allPiecesOfColor =
            'b': [0, 0, 0, 0]
            'w': [0, 0, 0, 0]
        @bitBoards.allPiecesOfColorAndType =
            'b':
                'r': [0, 0, 0, 0]
                'n': [0, 0, 0, 0]
                'b': [0, 0, 0, 0]
                'k': [0, 0, 0, 0]
                'q': [0, 0, 0, 0]
                'p': [0, 0, 0, 0]
            'w':
                'r': [0, 0, 0, 0]
                'n': [0, 0, 0, 0]
                'b': [0, 0, 0, 0]
                'k': [0, 0, 0, 0]
                'q': [0, 0, 0, 0]
                'p': [0, 0, 0, 0]

        for square, {color: color, type: type} of @pieces
            [quadrant, value] = CMGBitBoard.quadrantAndValueOfSquare( parseInt(square) )
            @bitBoards.allPieces[quadrant]                              |= value
            @bitBoards.allPiecesOfColor[color][quadrant]                |= value
            @bitBoards.allPiecesOfColorAndType[color][type][quadrant]   |= value

# =============================================================================

class CMGMove
    @fromPositionAndMoveString: (startPosition, moveString) ->
        ###
        @return (CMGMove|false) Returns a CMGMove instance if valid, false otherwise
        ###
        fromSquare = moveString.substr(0, 2)
        toString = moveString.substr(2, 2)
        promotion = false
        if moveString.length is 5
            promotion = moveString.substr(4)

        @fromPositionAndMoveCoordinates(startPosition, fromSquare, toSquare, promotion)

    @fromPositionAndMoveCoordinates: (startPosition, fromSquare, toSquare, promotion = false) ->
        ###
        @return (CMGMove|false) Returns a CMGMove instance if valid, false otherwise
        ###
        fromPiece = startPosition._getPieceOnSquare(fromSquare)

        toPiece = fromPiece.clone()
        if promotion isnt false
            toPiece.type = promotion

        castling = false
        if fromPiece.type is 'k'
            dist = toSquare - fromSquare
            castling = 'k' if dist is 2
            castling = 'q' if dist is -2

        takenPiece = false
        takenOnSquare = false
        landingSquareContent = startPosition._getPieceOnSquare(toSquare)
        if landingSquareContent
            takenPiece = landingSquareContent.clone()
            takenOnSquare = toSquare
        else if startPosition.enPassantSquare is toSquare
            takenPiece = new CMGPiece(startPosition.opponentColorCode(), 'p')
            if startPosition.enPassantSquare > 31
                takenOnSquare = startPosition.enPassantSquare - 8
            else
                takenOnSquare = startPosition.enPassantSquare + 8

        out = new CMGMove(startPosition, fromSquare, fromPiece, toSquare, toPiece, castling, takenPiece, takenOnSquare)

        if not out.isValid()
            return false

        return out

    constructor: (@startPosition, @fromSquare, @fromPiece, @toSquare, @toPiece, @castling = false, @takenPiece = false, @takenOnSquare = false) ->
        ###
        Constructor
        @param startPosition (CMGPosition)
        @param fromSquare (integer)
        @param fromPiece (CMGPiece)
        @param toSquare (integer)
        @param toPiece (CMGPiece)
        @param castling (false|"q"|"k")
        @param takenPiece (false|CMGPiece)
        @param takenOnSquare (false|integer)
        ###

        @lazy = {}

        @fromSquare     = CMGUtil.toString(@fromSquare)
        @toSquare       = CMGUtil.toString(@toSquare)
        @takenOnSquare  = CMGUtil.toString(@takenOnSquare)

    clone: () ->
        # Do not clone @startPosition in order to avoid circular references
        takenPiece = false
        if @takenPiece
            takenPiece = @takenPiece.clone()
        out = new CMGMove(@startPosition, @fromSquare, @fromPiece.clone(), @toSquare, @toPiece.clone(), @castling, takenPiece, @takenOnSquare)
        return out

    toString:   () ->
        out = CMGPosition.squareNumberToString(@fromSquare) + CMGPosition.squareNumberToString(@toSquare)
        if @fromPiece.type is 'p' and @toPiece.type isnt 'p'
            out += @toPiece.type.toUpperCase()
        out

    getNewPosition: () ->
        if not @lazy.hasOwnProperty('end-position')
            @lazy['end-position'] = @startPosition._getNewPositionObjectAfterMove(this)
        @lazy['end-position']

    isEnPassant: () ->
        clg.log('Taken piece is ' + @takenPiece + ' on square ' + @takenOnSquare)
        if @takenPiece is false
            return false

        return ( @takenOnSquare isnt @toSquare )

    isValid: () ->

        # First, test if it is a pseudo move
        isPseudoMove = false
        for pseudoMove in @startPosition._allPseudoMovesFromSquare(@fromSquare)
            if @toSquare isnt pseudoMove.toSquare
                continue
            if @toPiece isnt pseudoMove.toPiece
                continue
            if @castling isnt pseudoMove.castling
                continue
            if @takenPiece isnt pseudoMove.takenPiece
                continue
            if @takenOnSquare isnt pseudoMove.takenOnSquare
                continue
            isPseudoMove = true
            break

        return (isPseudoMove and @isValidPseudoMove() )

    isValidPseudoMove: () ->
        ###
        Assuming the move is a pseudo move of the start position, is it a valid one?
        We must eliminate:
        * pawn taking moves where nothing can be taken (verify also en passant)
        * move after which the king is under chess
        * castling moves that cross a threatened square
        ###

        if @fromPiece.type is 'p' and ( Math.abs(@toSquare - @fromSquare) % 8 ) isnt 0 and @takenPiece is false
            # A taking move with a pawn, but no piece has been taken
            return CMGPosition.PSEUDO_ONLY

        val = false
        if @startPosition.toString() is "r3k3/p1ppqpb1/1n2pnp1/3PN3/1p2P2r/2Nb1Q1p/PPPBKPPP/R6R w - - 0 2" and @fromSquare is '21' and @toSquare is '19'
            val = true
        clg.open(false)

        # The purpose of the following tests is to minimize the number of times @getNewPosition()._opponentKingAttacked() is called.
        doUnprotectionTest = true
        if @fromPiece.type is 'k'
            clg.log('King move ' + @toString())

            # King is moved, test if king under attack after move
            if @getNewPosition()._opponentKingAttacked() # opponent of new position, i.e. player of current position
                return CMGPosition.PSEUDO_ONLY

            doUnprotectionTest = false # Not necessary, since we already have tested the end position

        else if @isEnPassant()
            clg.log('En passant move ' + @toString())

            # Subsequent protection tests won't work. Test if king under attack after move
            if @getNewPosition()._opponentKingAttacked() # opponent of new position, i.e. player of current position
                return CMGPosition.PSEUDO_ONLY

            doUnprotectionTest = false # Not necessary, since we already have tested the end position

        else if not CMGBitBoard.boolNand( @startPosition.bitBoards.allPiecesOfColorAndType[@startPosition.turn]['k'], @startPosition._pseudoThreatsOnPlayerBeforeMove() )
            # King was under attack before move, test if king protected by landing square
            clg.log('king attacked before move ' + @toString())
            if not @startPosition._attackedKingProtectedByTargetSquareOfNonKingMove(this)
                clg.log('and not protected')
                return CMGPosition.PSEUDO_ONLY

        else
            # King was not under attack before move,
            clg.log('king NOT attacked before move ' + @toString())

        clg.log("doUnprotectionTest is " + doUnprotectionTest)

        if doUnprotectionTest
            # Test if king was protected by piece before move
            protectionDirection = @startPosition._directionOfKingProtectionByOriginatingSquareOfNonKingMove(this)
            clg.log("Protection direction is " + protectionDirection)
            if protectionDirection isnt false
                clg.log("King is protected by square #{@fromSquare} in direction #{protectionDirection}")

                # King may still be protected after move, if move is along protection direction
                testMoveDirection = true
                switch @fromPiece.type
                    when 'n' then testMoveDirection = false
                    when 'b' then testMoveDirection = ( protectionDirection % 2 isnt 0 )
                    when 'r' then testMoveDirection = ( protectionDirection % 2 is 0 )
                moveDirection = false
                if testMoveDirection
                    [moveDirection, dummy] = CMGPosition._direction(@fromSquare, @toSquare) # False if not along one of the 8 directions, e.g. for knights
                clg.log("Move direction is " + moveDirection)
                if ( moveDirection is false ) or ( Math.abs(moveDirection - protectionDirection) % 4 isnt 0 )
                    clg.log('King no longer protected after move')
                    return CMGPosition.PSEUDO_ONLY

        # Test if castling is allowed: the king may not be under chess before move, and it may not cross a field that is under chess
        if @fromPiece.type is 'k'
            delta = parseInt(@toSquare) - parseInt(@fromSquare)
            if Math.abs(delta) is 2
                castlingSide = 'k'
                if delta < 0
                    castlingSide = 'q'
                if not @startPosition._castlingPossibleOnSide(castlingSide)
                    return CMGPosition.PSEUDO_ONLY

        return true

# =============================================================================

class CMGPiece
    constructor: (@color, @type) ->
        ###
        Constructor
        @param color ("b"|"w") black or white
        @param type ("p"|"n"|b"|"r"|"q"|"k") pawn, knight, bishop, rook, queen or king
        ###

    # -------------------------------------------------------------------------
    # Public functions of class (comparable to static methods)

    @fromChar: (pieceChar) ->
        [color, piece] = CMGPiece._charToInternalRepresentation( pieceChar )

        return new CMGPiece( color, piece )

    # -------------------------------------------------------------------------
    # Protected functions of class (comparable to static methods)

    @_charToInternalRepresentation: (pieceChar) ->
        charCode = pieceChar.charCodeAt(0)
        color = 'b'
        piece = null
        if charCode < 97
            # Uppercase => transform and mark as white
            color = 'w'
            charCode += 32 # 97 - 65, i.e. code('a') - code('A')

        if charCode isnt 114 and charCode isnt 110 and charCode isnt 98 and charCode isnt 113 and charCode isnt 107 and charCode isnt 112
            # Not in r, n, b, q, k, p
            console.log("Invalid character code to represent a chess piece: #{charCode}")
            throw "Invalid character code to represent a chess piece: #{charCode}"

        return [color, String.fromCharCode(charCode)]

    # -------------------------------------------------------------------------
    # Public functions of object (comparable to non-static methods)

    toChar: () ->
        out = @type

        if @color is 'w'
            out = String.fromCharCode( @type.charCodeAt(0) - 32 ) # 97 - 65, i.e. code('a') - code('A')

        return out

    clone: () ->
        new CMGPiece(@color, @type)

# =============================================================================

class CMGUtil
    @cloneObject: (obj) ->
        ###
        Function to clone an object

        Source: http://keithdevens.com/weblog/archive/2007/Jun/07/javascript.clone
        ###
        if obj is null or (typeof obj) isnt 'object'
            return obj

        if (obj instanceof CMGPosition) or (obj instanceof CMGMove) or (obj instanceof CMGPiece)
            # Use specific clone function to avoid circular references
            return obj.clone()

        out = new obj.constructor

        for key, value of obj
            out[key] = @cloneObject(value)

        out

    @toString: (value) ->
        if typeof value isnt 'string'
            return '' + value

        return value

    @toInteger: (value) ->
        if typeof value is 'string'
            return parseInt(value)

        if typeof value isnt 'number'
            return 0 # Unknown

        if value % 1 isnt 0
            # Not an integer
            return Math.floor(value)

        return value

    @to0x88representation: (value) ->
        ###
        0x88 representation allows to detect borders easily
        todo unit test this
        ###
        value = @toInteger(value)
        for increment in [0..7]
            if value < 8 + 8 * increment
                return value + 8 * increment
        throw "Invalid value #{value}" # this should never happen


    @from0x88representation: (value) ->
        ###
        0x88 representation allows to detect borders easily
        todo unit test this
        ###
        value = @toInteger(value)
        for increment in [0..7]
            if value >= 112 - 16 * increment
                return value - 8 * (7 - increment)
        throw "Invalid value #{value}" # this should never happen



# =============================================================================
# Export the symbols that must be kept after clojure compiler's advanced optimization

NoCompile = {}

NoCompile.position = CMGPosition
NoCompile.position['fromString'] = CMGPosition.fromString
NoCompile.position.prototype['clone'] = CMGPosition.prototype.clone
NoCompile.position.prototype['playerColorCode'] = CMGPosition.prototype.playerColorCode
NoCompile.position.prototype['opponentColorCode'] = CMGPosition.prototype.opponentColorCode
NoCompile.position.prototype['toString'] = CMGPosition.prototype.toString
NoCompile.position.prototype['toStringWithoutCounters'] = CMGPosition.prototype.toStringWithoutCounters
NoCompile.position.prototype['allPossibleMovesFrom'] = CMGPosition.prototype.allPossibleMovesFrom
NoCompile.position.prototype['allPossibleMoves'] = CMGPosition.prototype.allPossibleMoves
NoCompile.position.prototype['isDraw'] = CMGPosition.prototype.isDraw
NoCompile.position.prototype['isValidMove'] = CMGPosition.prototype.isValidMove
NoCompile.position.prototype['getWinnerColorCode'] = CMGPosition.prototype.getWinnerColorCode

NoCompile.move = CMGMove
NoCompile.move['fromPositionAndMoveString'] = CMGMove.fromPositionAndMoveString
NoCompile.move['fromPositionAndMoveCoordinates'] = CMGMove.fromPositionAndMoveCoordinates
NoCompile.move.prototype['toString'] = CMGMove.prototype.toString
NoCompile.move.prototype['getNewPosition'] = CMGMove.prototype.getNewPosition

if typeof window isnt 'undefined'
    window['ChessPosition'] = NoCompile.position
    window['ChessMove'] = NoCompile.move

# =============================================================================
# Export the symbols that must be access via node.js

if typeof module isnt 'undefined'
    module['exports']['position'] = NoCompile.position
    module['exports']['move']     = NoCompile.move

